// The in-app questionnaires: data model, screen UI, and completion tracking.
//
// Generated from pipeline/instruments.py, which holds the item text, the response
// options, the scoring and the citations. Regenerate with:
//
//   python3 -m pipeline.cli emit-questionnaires
//
// Screen space, not VR. These run before and after the session with the headset off,
// which is the only sane place for free text and for a consent form somebody has to be
// able to re-read.
//
// NOTHING HERE BLOCKS. Every form can be skipped, and skipping proceeds to the next step
// rather than stalling the session. A questionnaire that blocks is one that gets answered
// carelessly to make it go away, and a researcher who is out of time will find some
// worse way around it. What the study gets instead is an honest record of what was and
// was not answered, and an end screen that names anything missing.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;

namespace EmotionRooms
{
    // ------------------------------------------------------------------ data model

    [Serializable]
    public class QuestionItem
    {
        public string id;
        public string type;          // choice | scale | text | paragraph
        public string text;
        public string help;
        public string[] options;
        public int min;
        public int max;
        public int step;
        public string min_label;
        public string max_label;
        public bool reversed;
        public string subscale;

        public int Step { get { return step > 0 ? step : 1; } }
    }

    [Serializable]
    public class QuestionForm
    {
        public string id;
        public string title;
        public string when;          // before | after
        public string citation;
        public string instruction;
        public QuestionItem[] items;
    }

    [Serializable]
    public class QuestionnaireSet
    {
        public int version;
        public QuestionForm[] forms;

        public static QuestionnaireSet FromJson(string json)
        {
            try { return JsonUtility.FromJson<QuestionnaireSet>(json); }
            catch (Exception e)
            {
                Debug.LogError("Questionnaire: could not parse questionnaires.json. " + e.Message);
                return null;
            }
        }
    }

    public enum FormState { NotShown, Completed, Skipped, PartlyAnswered }

    // ---------------------------------------------------------------------- runner

    public class QuestionnaireRunner : MonoBehaviour
    {
        [Tooltip("File in StreamingAssets. Generated by: python3 -m pipeline.cli emit-questionnaires")]
        public string fileName = "questionnaires.json";

        public string participantId = "p01";
        public EventLog events;
        public StudyTelemetry telemetry;

        [Tooltip("File written next to the other results, one row per answered item.")]
        public string responsesFileName = "questionnaire_responses.csv";

        /// <summary>Fires as each form closes, with its id and how it ended.</summary>
        public event Action<string, FormState> FormFinished;

        QuestionnaireSet set;
        readonly Dictionary<string, string> answers = new Dictionary<string, string>();
        readonly Dictionary<string, FormState> states = new Dictionary<string, FormState>();
        bool summaryVisible;

        void Start()
        {
            // ShippedAssets loads asynchronously because Android has to go through
            // UnityWebRequest, so this waits rather than reading an empty cache in Awake
            // and concluding there are no questionnaires.
            StartCoroutine(LoadWhenReady());
        }

        System.Collections.IEnumerator LoadWhenReady()
        {
            float deadline = Time.realtimeSinceStartup + 20f;
            while (!ShippedAssets.Ready && Time.realtimeSinceStartup < deadline)
                yield return null;
            Load();
        }

        void Load()
        {
            // Through ShippedAssets, because StreamingAssets is not a readable folder
            // on Android and this file has to survive a standalone headset build.
            string text = ShippedAssets.Get(fileName);
            if (text == null)
            {
                Debug.LogWarning("Questionnaire: no " + fileName + " in StreamingAssets. " +
                                 "Run: python3 -m pipeline.cli emit-questionnaires\n" +
                                 "The session will run without questionnaires.");
                return;
            }
            set = QuestionnaireSet.FromJson(text);
            if (set == null || set.forms == null) return;

            foreach (var form in set.forms) states[form.id] = FormState.NotShown;
        }

        /// <summary>Forms due at this point in the session, for the panel to offer.</summary>
        public List<QuestionForm> Due(string when)
        {
            var due = new List<QuestionForm>();
            if (set == null || set.forms == null) return due;
            foreach (var form in set.forms)
                if (form.when == when) due.Add(form);
            return due;
        }

        static string Key(QuestionForm form, QuestionItem item)
        {
            return form.id + "." + item.id;
        }

        // ------------------------------------------------------------------ writing

        string ResponsePath
        {
            get { return Path.Combine(Application.persistentDataPath, responsesFileName); }
        }

        void Write(QuestionForm form, int answered, float seconds)
        {
            try
            {
                if (!File.Exists(ResponsePath))
                {
                    File.WriteAllText(ResponsePath,
                        "participant,form,item,answer,reversed,subscale,state," +
                        "answered_items,total_items,seconds,utc\n", Encoding.UTF8);
                }

                var text = new StringBuilder();
                string utc = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture);
                string state = states[form.id].ToString();

                // A row per item, including unanswered ones. A missing row and a
                // deliberate non-answer look identical in a wide file, and "preferred not
                // to say" is data.
                foreach (var item in form.items)
                {
                    string value;
                    if (!answers.TryGetValue(Key(form, item), out value)) value = "";
                    text.Append(string.Join(",", new[]
                    {
                        participantId, form.id, item.id, Csv(value),
                        item.reversed ? "1" : "0", item.subscale ?? "", state,
                        answered.ToString(CultureInfo.InvariantCulture),
                        form.items.Length.ToString(CultureInfo.InvariantCulture),
                        seconds.ToString("0.0", CultureInfo.InvariantCulture), utc,
                    })).Append('\n');
                }
                File.AppendAllText(ResponsePath, text.ToString(), Encoding.UTF8);
            }
            catch (IOException e)
            {
                Debug.LogError("Questionnaire: could not write responses. " + e.Message);
            }
        }

        static string Csv(string value)
        {
            if (string.IsNullOrEmpty(value)) return "";
            if (value.IndexOf(',') < 0 && value.IndexOf('"') < 0 && value.IndexOf('\n') < 0)
                return value;
            return "\"" + value.Replace("\"", "\"\"").Replace("\n", " ") + "\"";
        }

        // ------------------------------------------------------------------- status

        /// <summary>True only if every consent statement was affirmed.</summary>
        public bool ConsentAffirmed()
        {
            if (set == null || set.forms == null) return false;
            foreach (var form in set.forms)
            {
                if (form.id != "consent") continue;
                foreach (var item in form.items)
                {
                    string value;
                    if (!answers.TryGetValue(Key(form, item), out value) || value != "Yes")
                        return false;
                }
                return true;
            }
            return false;
        }

        /// <summary>Every form, in order. For the server's index and the control panel.</summary>
        public IEnumerable<QuestionForm> AllForms()
        {
            if (set == null || set.forms == null) yield break;
            foreach (var form in set.forms) yield return form;
        }

        public QuestionForm Find(string formId)
        {
            if (set == null || set.forms == null || string.IsNullOrEmpty(formId)) return null;
            foreach (var form in set.forms) if (form.id == formId) return form;
            return null;
        }

        /// <summary>
        /// Record a submission from the browser form.
        ///
        /// Blank answers are kept as blanks rather than dropped. A question someone chose
        /// not to answer and a question that was never put to them look identical in a
        /// wide file otherwise, and only one of those is a problem.
        /// </summary>
        public void SubmitFromWeb(string formId, Dictionary<string, string> fields)
        {
            var form = Find(formId);
            if (form == null)
            {
                Debug.LogWarning("Questionnaire: submission for unknown form " + formId);
                return;
            }

            int answered = 0;
            foreach (var item in form.items)
            {
                string value;
                if (!fields.TryGetValue(item.id, out value) || string.IsNullOrEmpty(value))
                {
                    answers.Remove(Key(form, item));
                    continue;
                }
                answers[Key(form, item)] = value;
                answered++;
            }

            states[form.id] = answered == form.items.Length
                ? FormState.Completed
                : (answered > 0 ? FormState.PartlyAnswered : FormState.Skipped);

            Write(form, answered, 0f);

            if (telemetry != null) telemetry.Mark("form_submitted=" + form.id);
            if (events != null)
                events.WriteValues("form_submitted", form.id, states[form.id].ToString(), null);

            var handler = FormFinished;
            if (handler != null) handler(form.id, states[form.id]);

            Debug.Log("Questionnaire: " + form.title + " submitted (" + answered + " of " +
                      form.items.Length + " answered).");
        }

        public FormState StateOf(string formId)
        {
            FormState state;
            return states.TryGetValue(formId, out state) ? state : FormState.NotShown;
        }

        /// <summary>Forms that are not fully completed, by title. Empty when all are done.</summary>
        public List<string> Outstanding()
        {
            var missing = new List<string>();
            if (set == null || set.forms == null) return missing;

            foreach (var form in set.forms)
            {
                if (StateOf(form.id) == FormState.Completed) continue;
                missing.Add(form.title + "  (" + Describe(StateOf(form.id)) + ")");
            }
            return missing;
        }

        static string Describe(FormState state)
        {
            switch (state)
            {
                case FormState.Completed: return "done";
                case FormState.Skipped: return "skipped";
                case FormState.PartlyAnswered: return "partly answered";
                default: return "never shown";
            }
        }

        public void ShowSummary() { summaryVisible = true; }

        // ----------------------------------------------------------------------- UI

        void OnGUI()
        {
            // Only the end-of-session summary is drawn in the app now. The forms
            // themselves are browser pages served by FormServer, so nothing is answered
            // through the headset.
            if (summaryVisible) DrawSummary();
        }

        void DrawSummary()
        {
            float w = Mathf.Min(680f, Screen.width - 40f);
            var area = new Rect((Screen.width - w) / 2f, 60f, w, Screen.height - 120f);
            GUI.DrawTexture(area, Backdrop());
            GUI.Box(area, GUIContent.none);
            GUILayout.BeginArea(new Rect(area.x + 20f, area.y + 18f, area.width - 40f,
                                         area.height - 36f));

            GUILayout.Label("Session complete — " + participantId, Heading());

            var missing = Outstanding();
            if (missing.Count == 0)
            {
                GUILayout.Label("Every form was completed. Nothing outstanding.", Body());
            }
            else
            {
                GUILayout.Label("Not everything was completed. Outstanding:", Body());
                GUILayout.Space(6f);
                foreach (var line in missing) GUILayout.Label("   •  " + line, Body());
                GUILayout.Space(10f);
                GUILayout.Label(
                    "This is recorded, not a failure. Any form above can still be filled " +
                    "in on paper and entered later; note on the participant record which " +
                    "ones, so the gap is not mistaken for a missing file.", Fine());
            }

            GUILayout.Space(14f);
            GUILayout.Label("Thank you. Please take the headset off.", Body());
            GUILayout.EndArea();
        }

        static Texture2D backdrop;

        /// <summary>Opaque panel behind the end screen, so room geometry cannot show
        /// through the text.</summary>
        static Texture2D Backdrop()
        {
            if (backdrop != null) return backdrop;
            backdrop = new Texture2D(1, 1);
            backdrop.SetPixel(0, 0, new Color(0.11f, 0.11f, 0.13f, 0.97f));
            backdrop.Apply();
            backdrop.hideFlags = HideFlags.HideAndDontSave;
            return backdrop;
        }

        static GUIStyle heading, body, fine, chosen;

        static GUIStyle Chosen()
        {
            if (chosen == null)
                chosen = new GUIStyle(GUI.skin.button)
                {
                    fontStyle = FontStyle.Bold,
                    normal = { textColor = new Color(0.45f, 0.85f, 1f) },
                    hover = { textColor = new Color(0.45f, 0.85f, 1f) },
                };
            return chosen;
        }

        static readonly Color Ink = new Color(0.93f, 0.93f, 0.95f);
        static readonly Color Muted = new Color(0.68f, 0.68f, 0.72f);

        static GUIStyle Heading()
        {
            if (heading == null)
                heading = new GUIStyle(GUI.skin.label)
                {
                    fontSize = 21, fontStyle = FontStyle.Bold, normal = { textColor = Ink },
                };
            return heading;
        }

        static GUIStyle Body()
        {
            if (body == null)
                body = new GUIStyle(GUI.skin.label)
                {
                    fontSize = 15, wordWrap = true, normal = { textColor = Ink },
                };
            return body;
        }

        static GUIStyle Fine()
        {
            if (fine == null)
                fine = new GUIStyle(GUI.skin.label)
                {
                    fontSize = 12, wordWrap = true, normal = { textColor = Muted },
                };
            return fine;
        }
    }
}
