// A world-space multiple-choice panel, built from colliders and raycasts.
//
// Same approach as AffectGrid and for the same reason: a world-space Unity canvas in VR
// needs an event camera, an input module and a graphic raycaster all wired correctly, and
// when one of them is wrong it fails silently rather than loudly. A quad with a
// BoxCollider either gets hit or it does not.
//
// Without this the review block hangs: OversightReview waits on `detectionAnswered` and
// nothing can ever set it. Generated by Emotion Rooms > Set Up Study Scene.

using System;
using System.Collections.Generic;
using UnityEngine;

namespace EmotionRooms
{
    public class QuestionPanel : MonoBehaviour
    {
        [Serializable]
        public class Option
        {
            public string value;          // what gets logged
            public Transform target;      // the collider the pointer hits

            // Which variable this value belongs to, or null for ungrouped panels.
            // Exists because pool values collide as strings: 300 is both a hue (purple)
            // and an illuminance (300 lx). One shared "300" cell cannot wear both
            // faces, so the correction panel builds one cell per (field, value) and
            // shows only the attributed field's group.
            public string group;
        }

        [Tooltip("Question text. Set at runtime and rendered above the options.")]
        public string prompt = "";

        [Tooltip("Where the question is drawn. Built by scene setup.")]
        public TextMesh promptLabel;

        public List<Option> options = new List<Option>();

        [Tooltip("Optional 0..1 slider for confidence, built as a strip of cells.")]
        public Transform confidenceStrip;
        public int confidenceSteps = 5;

        [Tooltip("Ignore hits for this long after appearing, so a click meant for the " +
                 "previous screen cannot fall through into an answer.")]
        public float inputLockSeconds = 0.4f;

        [Tooltip("Every hover change, part-choice and commit becomes a row here. " +
                 "Decided 8 Aug 2026: the path to an answer is data, not noise.")]
        public EventLog events;

        /// <summary>Fires with the chosen option value and the confidence at the time.</summary>
        public event Action<string, float> Answered;

        public bool IsAwaitingAnswer { get; private set; }
        public float Confidence { get; private set; }

        float shownAt;
        Transform highlighted;

        // Two-part answering. The answer used to commit on the option press with the
        // confidence strip defaulting to 0.5 for anyone who never touched it -- which
        // fills the confidence column with a value nobody chose. Phase B scores
        // calibration from that column, so an unchosen default is not data. Nothing
        // resolves until both the option and, when a strip is present, a confidence
        // cell have been pressed, in either order.
        string pendingValue;
        bool confidenceChosen;
        Transform chosenOption, chosenConfidence;

        // Dark, not light. Idle cells were light grey with white labels: near-zero
        // contrast, and unreadable the moment a 750-lux room sat behind them. The
        // chosen-green state was the only readable one, which is how the problem was
        // finally noticed. A dark face carries white text over any room.
        static readonly Color IdleTint = new Color(0.16f, 0.17f, 0.20f);
        static readonly Color HoverTint = new Color(0.35f, 0.75f, 1f);
        static readonly Color ChosenTint = new Color(0.30f, 0.85f, 0.42f);

        void Awake()
        {
            Confidence = 0.5f;
            // No Hide() -- same deferred-Awake trap as AffectGrid: the panel is saved
            // inactive, so this Awake runs inside the first Show(), and a Hide() here
            // would cancel that Show and hang the review block on its first question.
        }

        public void Show(string questionText)
        {
            Show(questionText, null);
        }

        /// <summary>
        /// Show with only <paramref name="allowed"/> selectable, or all when null.
        ///
        /// The correction screen uses this: once someone has attributed the problem to
        /// brightness, offering them "textile" as a correction is not a choice they can
        /// meaningfully make, and a stray hit on it would land in the data as if it were.
        /// </summary>
        public void Show(string questionText, ICollection<string> allowed)
        {
            Show(questionText, allowed, null);
        }

        /// <summary>Show with only <paramref name="group"/>'s options selectable.</summary>
        public void Show(string questionText, ICollection<string> allowed, string group)
        {
            prompt = questionText ?? prompt;
            pendingValue = null;
            confidenceChosen = false;
            SetTint(chosenOption, false);
            SetTint(chosenConfidence, false);
            chosenOption = chosenConfidence = null;

            // The question has to be visible, not just stored. Without this the panel is
            // a row of unlabelled boxes and the participant is guessing at what is being
            // asked -- including which emotion the room was supposed to convey.
            if (promptLabel != null) WorldLabel.SetText(promptLabel, WorldLabel.Wrap(prompt));
            Confidence = 0.5f;
            IsAwaitingAnswer = true;
            shownAt = Time.time;

            foreach (var option in options)
            {
                if (option.target == null) continue;
                bool inGroup = group == null || option.group == group;
                option.target.gameObject.SetActive(
                    inGroup && (allowed == null || allowed.Contains(option.value)));
            }

            PlaceInFrontOfViewer();
            gameObject.SetActive(true);

            // A panel with nothing pressable is a hang, and it is silent.
            //
            // The block waits on an answer that cannot be given, the participant sees a
            // room and a question and no way to respond, and the researcher outside sees
            // a session that has simply stopped. Filtering by group and by allowed values
            // can land on an empty set, so say so loudly rather than wait forever.
            int pressable = 0;
            foreach (var option in options)
                if (option.target != null && option.target.gameObject.activeSelf) pressable++;
            if (pressable == 0)
                Debug.LogError("QuestionPanel " + name + ": no options are pressable for \"" +
                               prompt + "\" (group=" + (group ?? "none") + "). The session " +
                               "will wait here forever. This is a wiring or filter bug.");
        }

        public void Hide()
        {
            IsAwaitingAnswer = false;
            gameObject.SetActive(false);
        }

        /// <summary>Highlight whatever the pointer is over. Call every frame while up.</summary>
        public void Hover(Ray ray)
        {
            if (!IsAwaitingAnswer) return;

            Transform hit = Resolve(ray);
            if (hit == highlighted) return;

            if (highlighted != chosenOption && highlighted != chosenConfidence)
                SetTint(highlighted, false);
            if (hit != chosenOption && hit != chosenConfidence)
                SetTint(hit, true);
            highlighted = hit;

            // Only landings on a real target, at most one row per 150 ms. The ray
            // crossing a cell border jitters hover on and off many times a second and
            // wrote thousands of rows that said nothing the next row did not.
            if (events != null && hit != null &&
                Time.time - lastHoverLogged >= 0.15f)
            {
                lastHoverLogged = Time.time;
                events.WriteValues("panel_hover", name, hit.name, Elapsed());
            }
        }

        float lastHoverLogged;

        string Elapsed()
        {
            return "t_shown_ms=" + ((long)((Time.time - shownAt) * 1000f))
                       .ToString(System.Globalization.CultureInfo.InvariantCulture);
        }

        /// <summary>
        /// Register a press. Resolves only once every required part has been chosen.
        /// </summary>
        public bool TrySelect(Ray ray)
        {
            if (!IsAwaitingAnswer) return false;
            if (Time.time - shownAt < inputLockSeconds) return false;

            Transform hit = Resolve(ray);
            if (hit == null) return false;

            if (confidenceStrip != null && hit.IsChildOf(confidenceStrip))
            {
                int index = ConfidenceIndexOf(hit);
                if (index >= 0 && confidenceSteps > 1)
                {
                    Confidence = Mathf.Clamp01(index / (float)(confidenceSteps - 1));
                    confidenceChosen = true;
                    SetTint(chosenConfidence, false);
                    chosenConfidence = hit;
                    Paint(chosenConfidence, ChosenTint);
                    if (events != null)
                        events.WriteValues("panel_confidence_chosen", name,
                            Confidence.ToString("0.##"), Elapsed());
                }
                return CommitIfComplete();
            }

            foreach (var option in options)
            {
                if (option.target != hit) continue;

                pendingValue = option.value;
                SetTint(chosenOption, false);
                chosenOption = hit;
                Paint(chosenOption, ChosenTint);
                if (events != null)
                    events.WriteValues("panel_option_chosen", name, option.value, Elapsed());
                return CommitIfComplete();
            }
            return false;
        }

        [Tooltip("The confidence cells in order, filled by scene setup. Their ORDER is " +
                 "the scale, which is why they are a list and not children of a strip.")]
        public List<Transform> confidenceCells = new List<Transform>();

        /// <summary>
        /// Which confidence step was hit, or -1 for a press on the strip but not a cell.
        ///
        /// This used to be the hit's sibling index under the strip, and the strip's first
        /// child is the "How sure are you?" caption. So the five cells were siblings one
        /// through five, and index/(steps-1) produced 0.25, 0.5, 0.75, 1.0 and 1.25
        /// clamped to 1.0: the scale could never return zero and its top two steps were
        /// the same number. Every confidence value collected so far is on that scale.
        ///
        /// Sibling index was also fragile in a way that could hang a session. A cell
        /// carries a label child, and anything that put a collider on a descendant would
        /// give a hit whose sibling index is -1 -- inside the strip by IsChildOf, not a
        /// cell by index -- so the press registered as nothing, confidenceChosen stayed
        /// false, and the panel waited for a confidence it had already been given. There
        /// is no way out of that from inside the headset.
        ///
        /// A registered list and a walk up the parents removes both.
        /// </summary>
        int ConfidenceIndexOf(Transform hit)
        {
            for (var node = hit; node != null && node != confidenceStrip; node = node.parent)
            {
                int found = confidenceCells.IndexOf(node);
                if (found >= 0) return found;
            }
            return -1;
        }

        [Tooltip("Whose view the panel places itself in front of. Wired by scene setup.")]
        public Camera viewer;

        [Tooltip("Metres in front of the participant when it appears.")]
        public float distance = 1.2f;

        /// <summary>
        /// Put the panel where the participant is actually looking, each time it appears.
        ///
        /// It used to be positioned once when the scene was generated, at wherever the
        /// camera happened to be then, and never moved again. That is fine only if the
        /// participant is standing exactly where the scene builder assumed. They are
        /// not: a floor-referenced pose puts somebody wherever they physically are in
        /// their own room, so the panel ends up off to one side and turned away, and the
        /// buttons are read at an angle. Akbar hit exactly that -- questions "shown
        /// sideways" and hard to read.
        ///
        /// Placed on Show and then left alone. A panel that chased the head every frame
        /// would be unreadable and could not be pointed at, since aiming requires the
        /// target to hold still.
        /// </summary>
        void PlaceInFrontOfViewer()
        {
            var camera = viewer != null ? viewer : Camera.main;
            if (camera == null) return;

            var forward = camera.transform.forward;
            forward.y = 0f;
            if (forward.sqrMagnitude < 0.0001f) return;
            forward.Normalize();

            transform.position = camera.transform.position + forward * distance;
            transform.rotation = Quaternion.LookRotation(forward);
        }

        bool StripRequired()        bool StripRequired()
        {
            return confidenceStrip != null && confidenceStrip.gameObject.activeInHierarchy;
        }

        bool CommitIfComplete()
        {
            if (pendingValue == null) return false;
            if (StripRequired() && !confidenceChosen) return false;

            IsAwaitingAnswer = false;
            SetTint(highlighted, false);
            SetTint(chosenOption, false);
            SetTint(chosenConfidence, false);
            highlighted = chosenOption = chosenConfidence = null;

            if (events != null)
                events.WriteValues("panel_committed", name,
                    pendingValue + "@" + Confidence.ToString("0.##"), Elapsed());

            var handler = Answered;
            if (handler != null) handler(pendingValue, Confidence);
            return true;
        }

        /// <summary>
        /// Answer a two-option question with a controller button.
        ///
        /// Pointing a ray at a box to say yes or no is more work than the question
        /// deserves, and it fails in the ways a ray fails: the beam is off, the box is
        /// small, the hand drifts. A button cannot miss. Kept to two options because
        /// beyond that there is no obvious mapping and the ray is the honest instrument.
        /// </summary>
        public bool TrySelectOption(int index)
        {
            if (!IsAwaitingAnswer) return false;
            if (Time.time - shownAt < inputLockSeconds) return false;
            if (index < 0 || index >= options.Count) return false;
            if (options[index].target != null && !options[index].target.gameObject.activeSelf)
                return false;

            IsAwaitingAnswer = false;
            SetTint(highlighted, false);
            SetTint(chosenOption, false);
            SetTint(chosenConfidence, false);
            highlighted = chosenOption = chosenConfidence = null;

            var handler = Answered;
            if (handler != null) handler(options[index].value, Confidence);
            return true;
        }

        /// <summary>How many options are actually offered right now.</summary>
        public int VisibleOptionCount()
        {
            int count = 0;
            foreach (var option in options)
                if (option.target == null || option.target.gameObject.activeSelf) count++;
            return count;
        }

        Transform Resolve(Ray ray)
        {
            // RaycastAll, not Raycast. A single Raycast returns the nearest collider in
            // the scene, so a room surface or a piece of furniture between the pointer
            // and the panel would swallow the hit and the panel would read it as a miss.
            // The participant then clicks a button that visibly highlights and nothing
            // happens, forever, because the review block is blocked waiting on an answer.
            // Considering only this panel's own colliders removes that whole class.
            //
            // QueryTriggerInteraction.Collide because the option colliders are triggers,
            // so they cannot shove the participant's rig around if it ever moves.
            var hits = Physics.RaycastAll(ray, 100f, ~0, QueryTriggerInteraction.Collide);

            Transform nearest = null;
            float nearestDistance = float.MaxValue;
            for (int i = 0; i < hits.Length; i++)
            {
                if (!hits[i].transform.IsChildOf(transform)) continue;
                if (hits[i].distance >= nearestDistance) continue;
                nearest = hits[i].transform;
                nearestDistance = hits[i].distance;
            }
            return nearest;
        }

        static void SetTint(Transform t, bool on)
        {
            Paint(t, on ? HoverTint : IdleTint);
        }

        static void Paint(Transform t, Color colour)
        {
            if (t == null) return;
            var renderer = t.GetComponent<Renderer>();
            if (renderer == null || renderer.material == null) return;
            renderer.material.color = colour;
        }
    }

    static class TransformSiblingExtensions
    {
        /// <summary>Index of `child` among `parent`'s direct children, or -1.</summary>
        public static int GetSiblingIndexOf(this Transform parent, Transform child)
        {
            for (int i = 0; i < parent.childCount; i++)
            {
                if (parent.GetChild(i) == child) return i;
            }
            return -1;
        }
    }
}
