// A world-space multiple-choice panel, built from colliders and raycasts.
//
// Same approach as AffectGrid and for the same reason: a world-space Unity canvas in VR
// needs an event camera, an input module and a graphic raycaster all wired correctly, and
// when one of them is wrong it fails silently rather than loudly. A quad with a
// BoxCollider either gets hit or it does not.
//
// Without this the review block hangs: OversightReview waits on `detectionAnswered` and
// nothing can ever set it. Generated by Emotion Rooms > Set Up Study Scene.

using System;
using System.Collections.Generic;
using UnityEngine;

namespace EmotionRooms
{
    public class QuestionPanel : MonoBehaviour
    {
        [Serializable]
        public class Option
        {
            public string value;          // what gets logged
            public Transform target;      // the collider the pointer hits
        }

        [Tooltip("Question text. Set at runtime; [emotion] is replaced with the target.")]
        public string prompt = "";

        public List<Option> options = new List<Option>();

        [Tooltip("Optional 0..1 slider for confidence, built as a strip of cells.")]
        public Transform confidenceStrip;
        public int confidenceSteps = 5;

        [Tooltip("Ignore hits for this long after appearing, so a click meant for the " +
                 "previous screen cannot fall through into an answer.")]
        public float inputLockSeconds = 0.4f;

        /// <summary>Fires with the chosen option value and the confidence at the time.</summary>
        public event Action<string, float> Answered;

        public bool IsAwaitingAnswer { get; private set; }
        public float Confidence { get; private set; }

        float shownAt;
        Transform highlighted;

        void Awake()
        {
            Confidence = 0.5f;
            Hide();
        }

        public void Show(string questionText)
        {
            Show(questionText, null);
        }

        /// <summary>
        /// Show with only <paramref name="allowed"/> selectable, or all when null.
        ///
        /// The correction screen uses this: once someone has attributed the problem to
        /// brightness, offering them "textile" as a correction is not a choice they can
        /// meaningfully make, and a stray hit on it would land in the data as if it were.
        /// </summary>
        public void Show(string questionText, ICollection<string> allowed)
        {
            prompt = questionText ?? prompt;
            Confidence = 0.5f;
            IsAwaitingAnswer = true;
            shownAt = Time.time;

            foreach (var option in options)
            {
                if (option.target == null) continue;
                option.target.gameObject.SetActive(allowed == null || allowed.Contains(option.value));
            }

            gameObject.SetActive(true);
        }

        public void Hide()
        {
            IsAwaitingAnswer = false;
            gameObject.SetActive(false);
        }

        /// <summary>Highlight whatever the pointer is over. Call every frame while up.</summary>
        public void Hover(Ray ray)
        {
            if (!IsAwaitingAnswer) return;

            Transform hit = Resolve(ray);
            if (hit == highlighted) return;

            SetTint(highlighted, false);
            SetTint(hit, true);
            highlighted = hit;
        }

        /// <summary>Commit. Returns false on a miss or during the input lock.</summary>
        public bool TrySelect(Ray ray)
        {
            if (!IsAwaitingAnswer) return false;
            if (Time.time - shownAt < inputLockSeconds) return false;

            Transform hit = Resolve(ray);
            if (hit == null) return false;

            // Confidence strip: setting confidence is not answering, so the panel stays
            // up. Otherwise a participant adjusting confidence would submit by accident.
            if (confidenceStrip != null && hit.IsChildOf(confidenceStrip))
            {
                int index = confidenceStrip.GetSiblingIndexOf(hit);
                if (index >= 0 && confidenceSteps > 1)
                {
                    Confidence = Mathf.Clamp01(index / (float)(confidenceSteps - 1));
                }
                return false;
            }

            foreach (var option in options)
            {
                if (option.target != hit) continue;

                IsAwaitingAnswer = false;
                SetTint(highlighted, false);
                highlighted = null;

                var handler = Answered;
                if (handler != null) handler(option.value, Confidence);
                return true;
            }
            return false;
        }

        Transform Resolve(Ray ray)
        {
            // RaycastAll, not Raycast. A single Raycast returns the nearest collider in
            // the scene, so a room surface or a piece of furniture between the pointer
            // and the panel would swallow the hit and the panel would read it as a miss.
            // The participant then clicks a button that visibly highlights and nothing
            // happens, forever, because the review block is blocked waiting on an answer.
            // Considering only this panel's own colliders removes that whole class.
            //
            // QueryTriggerInteraction.Collide because the option colliders are triggers,
            // so they cannot shove the participant's rig around if it ever moves.
            var hits = Physics.RaycastAll(ray, 100f, ~0, QueryTriggerInteraction.Collide);

            Transform nearest = null;
            float nearestDistance = float.MaxValue;
            for (int i = 0; i < hits.Length; i++)
            {
                if (!hits[i].transform.IsChildOf(transform)) continue;
                if (hits[i].distance >= nearestDistance) continue;
                nearest = hits[i].transform;
                nearestDistance = hits[i].distance;
            }
            return nearest;
        }

        static void SetTint(Transform t, bool on)
        {
            if (t == null) return;
            var renderer = t.GetComponent<Renderer>();
            if (renderer == null || renderer.material == null) return;
            renderer.material.color = on
                ? new Color(0.35f, 0.75f, 1f)
                : new Color(0.85f, 0.85f, 0.85f);
        }
    }

    static class TransformSiblingExtensions
    {
        /// <summary>Index of `child` among `parent`'s direct children, or -1.</summary>
        public static int GetSiblingIndexOf(this Transform parent, Transform child)
        {
            for (int i = 0; i < parent.childCount; i++)
            {
                if (parent.GetChild(i) == child) return i;
            }
            return -1;
        }
    }
}
