// The in-app questionnaires: data model, screen UI, and completion tracking.
//
// Generated from pipeline/instruments.py, which holds the item text, the response
// options, the scoring and the citations. Regenerate with:
//
//   python3 -m pipeline.cli emit-questionnaires
//
// Screen space, not VR. These run before and after the session with the headset off,
// which is the only sane place for free text and for a consent form somebody has to be
// able to re-read.
//
// NOTHING HERE BLOCKS. Every form can be skipped, and skipping proceeds to the next step
// rather than stalling the session. A questionnaire that blocks is one that gets answered
// carelessly to make it go away, and a researcher who is out of time will find some
// worse way around it. What the study gets instead is an honest record of what was and
// was not answered, and an end screen that names anything missing.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;

namespace EmotionRooms
{
    // ------------------------------------------------------------------ data model

    [Serializable]
    public class QuestionItem
    {
        public string id;
        public string type;          // choice | scale | text | paragraph
        public string text;
        public string help;
        public string[] options;
        public int min;
        public int max;
        public int step;
        public string min_label;
        public string max_label;
        public bool reversed;
        public string subscale;

        public int Step { get { return step > 0 ? step : 1; } }
    }

    [Serializable]
    public class QuestionForm
    {
        public string id;
        public string title;
        public string when;          // before | after
        public string citation;
        public string instruction;
        public QuestionItem[] items;
    }

    [Serializable]
    public class QuestionnaireSet
    {
        public int version;
        public QuestionForm[] forms;

        public static QuestionnaireSet FromJson(string json)
        {
            try { return JsonUtility.FromJson<QuestionnaireSet>(json); }
            catch (Exception e)
            {
                Debug.LogError("Questionnaire: could not parse questionnaires.json. " + e.Message);
                return null;
            }
        }
    }

    public enum FormState { NotShown, Completed, Skipped, PartlyAnswered }

    // ---------------------------------------------------------------------- runner

    public class QuestionnaireRunner : MonoBehaviour
    {
        [Tooltip("File in StreamingAssets. Generated by: python3 -m pipeline.cli emit-questionnaires")]
        public string fileName = "questionnaires.json";

        public string participantId = "p01";
        public EventLog events;
        public StudyTelemetry telemetry;

        [Tooltip("File written next to the other results, one row per answered item.")]
        public string responsesFileName = "questionnaire_responses.csv";

        public bool IsShowing { get { return current != null; } }

        /// <summary>Fires when the current batch of forms is done or skipped past.</summary>
        public event Action BatchFinished;

        /// <summary>Fires as each form closes, with its id and how it ended.</summary>
        public event Action<string, FormState> FormFinished;

        QuestionnaireSet set;
        readonly Queue<QuestionForm> pending = new Queue<QuestionForm>();
        QuestionForm current;
        readonly Dictionary<string, string> answers = new Dictionary<string, string>();
        readonly Dictionary<string, FormState> states = new Dictionary<string, FormState>();
        Vector2 scroll;
        float shownAt;
        bool summaryVisible;

        void Awake()
        {
            Load();
        }

        void Load()
        {
            string path = Path.Combine(Application.streamingAssetsPath, fileName);
            if (!File.Exists(path))
            {
                Debug.LogWarning("Questionnaire: no " + fileName + " in StreamingAssets. " +
                                 "Run: python3 -m pipeline.cli emit-questionnaires\n" +
                                 "The session will run without questionnaires.");
                return;
            }
            set = QuestionnaireSet.FromJson(File.ReadAllText(path));
            if (set == null || set.forms == null) return;

            foreach (var form in set.forms) states[form.id] = FormState.NotShown;
        }

        /// <summary>Queue every form marked for this point. Returns false if there are none,
        /// so the caller can carry straight on rather than waiting for a screen that will
        /// never appear.</summary>
        public bool Begin(string when)
        {
            if (set == null || set.forms == null) return false;

            pending.Clear();
            foreach (var form in set.forms)
                if (form.when == when) pending.Enqueue(form);

            if (pending.Count == 0) return false;
            Next();
            return true;
        }

        void Next()
        {
            if (pending.Count == 0)
            {
                current = null;
                var handler = BatchFinished;
                if (handler != null) handler();
                return;
            }
            current = pending.Dequeue();
            scroll = Vector2.zero;
            shownAt = Time.unscaledTime;

            if (telemetry != null) telemetry.Mark("form_shown=" + current.id);
            if (events != null) events.WriteValues("form_shown", current.id, null, null);
        }

        void Finish(bool skipped)
        {
            if (current == null) return;

            int answered = 0;
            foreach (var item in current.items)
                if (answers.ContainsKey(Key(current, item))) answered++;

            states[current.id] = skipped
                ? (answered > 0 ? FormState.PartlyAnswered : FormState.Skipped)
                : (answered == current.items.Length ? FormState.Completed : FormState.PartlyAnswered);

            Write(current, answered, Time.unscaledTime - shownAt);

            if (telemetry != null) telemetry.Mark("form_done=" + current.id);
            if (events != null)
                events.WriteValues("form_done", current.id, states[current.id].ToString(), null);

            var finished = FormFinished;
            if (finished != null) finished(current.id, states[current.id]);

            Next();
        }

        static string Key(QuestionForm form, QuestionItem item)
        {
            return form.id + "." + item.id;
        }

        // ------------------------------------------------------------------ writing

        string ResponsePath
        {
            get { return Path.Combine(Application.persistentDataPath, responsesFileName); }
        }

        void Write(QuestionForm form, int answered, float seconds)
        {
            try
            {
                if (!File.Exists(ResponsePath))
                {
                    File.WriteAllText(ResponsePath,
                        "participant,form,item,answer,reversed,subscale,state," +
                        "answered_items,total_items,seconds,utc\n", Encoding.UTF8);
                }

                var text = new StringBuilder();
                string utc = DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture);
                string state = states[form.id].ToString();

                // A row per item, including unanswered ones. A missing row and a
                // deliberate non-answer look identical in a wide file, and "preferred not
                // to say" is data.
                foreach (var item in form.items)
                {
                    string value;
                    if (!answers.TryGetValue(Key(form, item), out value)) value = "";
                    text.Append(string.Join(",", new[]
                    {
                        participantId, form.id, item.id, Csv(value),
                        item.reversed ? "1" : "0", item.subscale ?? "", state,
                        answered.ToString(CultureInfo.InvariantCulture),
                        form.items.Length.ToString(CultureInfo.InvariantCulture),
                        seconds.ToString("0.0", CultureInfo.InvariantCulture), utc,
                    })).Append('\n');
                }
                File.AppendAllText(ResponsePath, text.ToString(), Encoding.UTF8);
            }
            catch (IOException e)
            {
                Debug.LogError("Questionnaire: could not write responses. " + e.Message);
            }
        }

        static string Csv(string value)
        {
            if (string.IsNullOrEmpty(value)) return "";
            if (value.IndexOf(',') < 0 && value.IndexOf('"') < 0 && value.IndexOf('\n') < 0)
                return value;
            return "\"" + value.Replace("\"", "\"\"").Replace("\n", " ") + "\"";
        }

        // ------------------------------------------------------------------- status

        /// <summary>True only if every consent statement was affirmed.</summary>
        public bool ConsentAffirmed()
        {
            if (set == null || set.forms == null) return false;
            foreach (var form in set.forms)
            {
                if (form.id != "consent") continue;
                foreach (var item in form.items)
                {
                    string value;
                    if (!answers.TryGetValue(Key(form, item), out value) || value != "Yes")
                        return false;
                }
                return true;
            }
            return false;
        }

        public FormState StateOf(string formId)
        {
            FormState state;
            return states.TryGetValue(formId, out state) ? state : FormState.NotShown;
        }

        /// <summary>Forms that are not fully completed, by title. Empty when all are done.</summary>
        public List<string> Outstanding()
        {
            var missing = new List<string>();
            if (set == null || set.forms == null) return missing;

            foreach (var form in set.forms)
            {
                if (StateOf(form.id) == FormState.Completed) continue;
                bool onScreen = current != null && current.id == form.id;
                missing.Add(form.title + "  (" +
                            (onScreen ? "on screen now" : Describe(StateOf(form.id))) + ")");
            }
            return missing;
        }

        static string Describe(FormState state)
        {
            switch (state)
            {
                case FormState.Completed: return "done";
                case FormState.Skipped: return "skipped";
                case FormState.PartlyAnswered: return "partly answered";
                default: return "never shown";
            }
        }

        public void ShowSummary() { summaryVisible = true; }

        // ----------------------------------------------------------------------- UI

        void OnGUI()
        {
            if (summaryVisible) { DrawSummary(); return; }
            if (current == null) return;

            // Explicit rects for the header and the footer, with the scroll view given
            // exactly what is left over.
            //
            // The first version laid all three out in one GUILayout flow with the
            // instruction text above the scroll view. The consent instruction is six
            // paragraphs, so it consumed the whole area, and GUILayout handed the scroll
            // view and the buttons nothing -- the questions and both buttons were pushed
            // off the bottom of the screen. The form rendered, could not be answered, and
            // could not be skipped either. Reserving the footer first means the buttons
            // exist no matter how long the content is.
            float w = Mathf.Min(820f, Screen.width - 40f);
            float h = Screen.height - 60f;
            var area = new Rect((Screen.width - w) / 2f, 30f, w, h);

            // Opaque, so room geometry behind the form cannot show through the text.
            GUI.DrawTexture(area, Backdrop());
            GUI.Box(area, GUIContent.none);

            const float pad = 18f;
            const float footer = 46f;

            var header = new Rect(area.x + pad, area.y + 12f, area.width - pad * 2f, 34f);
            GUI.Label(header, current.title, Heading());

            var body = new Rect(area.x + pad, header.yMax + 6f, area.width - pad * 2f,
                                area.height - header.height - footer - 30f);
            var footerRect = new Rect(area.x + pad, area.yMax - footer,
                                      area.width - pad * 2f, footer - 10f);

            GUILayout.BeginArea(body);
            scroll = GUILayout.BeginScrollView(scroll);

            // Instruction inside the scroll view, so a long consent text scrolls rather
            // than crowding the questions out.
            if (!string.IsNullOrEmpty(current.instruction))
            {
                GUILayout.Label(current.instruction, Body());
                GUILayout.Space(10f);
            }
            foreach (var item in current.items) DrawItem(current, item);
            GUILayout.Space(12f);

            GUILayout.EndScrollView();
            GUILayout.EndArea();

            GUILayout.BeginArea(footerRect);
            GUILayout.BeginHorizontal();

            if (GUILayout.Button("Skip this form", GUILayout.Height(30f), GUILayout.Width(160f)))
                Finish(true);

            GUILayout.FlexibleSpace();
            GUILayout.BeginVertical();
            GUILayout.Space(6f);
            GUILayout.Label(Progress(), Fine());
            GUILayout.EndVertical();
            GUILayout.FlexibleSpace();

            if (GUILayout.Button("Continue", GUILayout.Height(30f), GUILayout.Width(160f)))
                Finish(false);

            GUILayout.EndHorizontal();
            GUILayout.EndArea();
        }

        string Progress()
        {
            int answered = 0;
            foreach (var item in current.items)
                if (answers.ContainsKey(Key(current, item))) answered++;
            return answered + " of " + current.items.Length + " answered" +
                   (pending.Count > 0 ? "   ·   " + pending.Count + " more forms" : "");
        }

        static Texture2D backdrop;

        static Texture2D Backdrop()
        {
            if (backdrop != null) return backdrop;
            backdrop = new Texture2D(1, 1);
            backdrop.SetPixel(0, 0, new Color(0.11f, 0.11f, 0.13f, 0.97f));
            backdrop.Apply();
            backdrop.hideFlags = HideFlags.HideAndDontSave;
            return backdrop;
        }

        void DrawItem(QuestionForm form, QuestionItem item)
        {
            string key = Key(form, item);
            string value;
            answers.TryGetValue(key, out value);

            GUILayout.Space(10f);
            if (!string.IsNullOrEmpty(item.text)) GUILayout.Label(item.text, Body());
            if (!string.IsNullOrEmpty(item.help)) GUILayout.Label(item.help, Fine());

            switch (item.type)
            {
                case "choice":
                    GUILayout.BeginHorizontal();
                    foreach (var option in item.options)
                    {
                        bool on = value == option;
                        // A button rather than a tick box: on a dark backdrop the default
                        // toggle glyph and its label are nearly invisible, and a chosen
                        // answer has to be obvious to the person who chose it.
                        var style = on ? Chosen() : GUI.skin.button;
                        if (GUILayout.Button((on ? "● " : "○ ") + option, style,
                                             GUILayout.Width(160f), GUILayout.Height(26f)))
                            answers[key] = option;
                    }
                    GUILayout.FlexibleSpace();
                    GUILayout.EndHorizontal();
                    break;

                case "scale":
                {
                    GUILayout.BeginHorizontal();
                    GUILayout.Label(item.min_label ?? "", Fine(), GUILayout.Width(120f));
                    for (int v = item.min; v <= item.max; v += item.Step)
                    {
                        string label = v.ToString(CultureInfo.InvariantCulture);
                        bool on = value == label;
                        // Narrow buttons so a 21-point TLX scale fits on one line.
                        float width = (item.max - item.min) / item.Step > 10 ? 26f : 36f;
                        if (GUILayout.Button(label, on ? Chosen() : GUI.skin.button,
                                             GUILayout.Width(width), GUILayout.Height(24f)))
                            answers[key] = label;
                    }
                    GUILayout.Label(item.max_label ?? "", Fine(), GUILayout.Width(120f));
                    GUILayout.EndHorizontal();
                    break;
                }

                case "paragraph":
                    answers[key] = GUILayout.TextArea(value ?? "", GUILayout.Height(56f));
                    break;

                default:
                    answers[key] = GUILayout.TextField(value ?? "", GUILayout.Height(20f));
                    break;
            }
        }

        void DrawSummary()
        {
            float w = Mathf.Min(680f, Screen.width - 40f);
            var area = new Rect((Screen.width - w) / 2f, 60f, w, Screen.height - 120f);
            GUI.DrawTexture(area, Backdrop());
            GUI.Box(area, GUIContent.none);
            GUILayout.BeginArea(new Rect(area.x + 20f, area.y + 18f, area.width - 40f,
                                         area.height - 36f));

            GUILayout.Label("Session complete — " + participantId, Heading());

            var missing = Outstanding();
            if (missing.Count == 0)
            {
                GUILayout.Label("Every form was completed. Nothing outstanding.", Body());
            }
            else
            {
                GUILayout.Label("Not everything was completed. Outstanding:", Body());
                GUILayout.Space(6f);
                foreach (var line in missing) GUILayout.Label("   •  " + line, Body());
                GUILayout.Space(10f);
                GUILayout.Label(
                    "This is recorded, not a failure. Any form above can still be filled " +
                    "in on paper and entered later; note on the participant record which " +
                    "ones, so the gap is not mistaken for a missing file.", Fine());
            }

            GUILayout.Space(14f);
            GUILayout.Label("Thank you. Please take the headset off.", Body());
            GUILayout.EndArea();
        }

        static GUIStyle heading, body, fine, chosen;

        static GUIStyle Chosen()
        {
            if (chosen == null)
                chosen = new GUIStyle(GUI.skin.button)
                {
                    fontStyle = FontStyle.Bold,
                    normal = { textColor = new Color(0.45f, 0.85f, 1f) },
                    hover = { textColor = new Color(0.45f, 0.85f, 1f) },
                };
            return chosen;
        }

        static readonly Color Ink = new Color(0.93f, 0.93f, 0.95f);
        static readonly Color Muted = new Color(0.68f, 0.68f, 0.72f);

        static GUIStyle Heading()
        {
            if (heading == null)
                heading = new GUIStyle(GUI.skin.label)
                {
                    fontSize = 21, fontStyle = FontStyle.Bold, normal = { textColor = Ink },
                };
            return heading;
        }

        static GUIStyle Body()
        {
            if (body == null)
                body = new GUIStyle(GUI.skin.label)
                {
                    fontSize = 15, wordWrap = true, normal = { textColor = Ink },
                };
            return body;
        }

        static GUIStyle Fine()
        {
            if (fine == null)
                fine = new GUIStyle(GUI.skin.label)
                {
                    fontSize = 12, wordWrap = true, normal = { textColor = Muted },
                };
            return fine;
        }
    }
}
