// Starts the session and drives pointer input into the affect grid.
//
// AffectGrid exposes Hover(), TryMark() and Commit() but deliberately does not read input
// itself: what counts as "pointing" differs between a controller ray, a gaze cursor and
// a mouse in the editor, and burying one of those inside the instrument would make the
// other two awkward. This is the piece that decides.
//
// Attach to one GameObject in the scene and wire the three references. Nothing else in
// the study needs an input dependency.
//
// Editor testing works out of the box with the mouse. For the headset, point
// `pointerOrigin` at your controller's ray transform and call Select() from whatever
// input system you use, or leave `useLegacyInput` on if your rig maps the trigger to a
// legacy button.

using System;
using System.Collections;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;

namespace EmotionRooms
{
    public class StudyBootstrap : MonoBehaviour
    {
        [Header("Wiring")]
        public TrialRunner trialRunner;

        [Tooltip("Raw input stream target. Every trigger press lands here as a row.")]
        public EventLog events;

        [Tooltip("Pilot sessions only, set from the control panel and never by default: " +
                 "shows an overhead SKIP THIS PART button. It abandons the running part " +
                 "and fires its normal completion, so chaining and bundling behave as if " +
                 "the part had finished. Real sessions never see it.")]
        public bool pilotMode;
        public OversightReview oversightReview;

        [Tooltip("The rationale check. Runs after the oversight block, ~3 minutes.")]
        public RationaleReview rationaleReview;
        public AffectGrid grid;

        [Tooltip("In-app forms. Runs the 'before' set on Begin Study and the 'after' set " +
                 "once the review block ends. Never blocks: every form can be skipped.")]
        public QuestionnaireRunner questionnaires;

        [Tooltip("World-space text, so the participant can be told something in VR. " +
                 "IMGUI does not render into an immersive view.")]
        public MessageBoard board;

        [Header("Review panels")]
        [Tooltip("Generated by Emotion Rooms > Set Up Study Scene. Without these the " +
                 "review block waits forever for an answer that can never arrive.")]
        public QuestionPanel detectionPanel;
        public QuestionPanel attributionPanel;
        public QuestionPanel correctionPanel;

        [Tooltip("Head and controller tracking on the headset. Inert with no headset, " +
                 "so the same scene still runs on a laptop with a mouse.")]
        public XRRig xrRig;

        [Header("Pointer")]
        [Tooltip("Transform whose forward axis is the pointing ray. A controller's ray " +
                 "origin in the headset. Leave empty in the editor and the mouse is used.")]
        public Transform pointerOrigin;

        [Tooltip("Camera used to build the ray when pointerOrigin is empty. Defaults to " +
                 "Camera.main.")]
        public Camera fallbackCamera;

        [Header("Input")]
        [Tooltip("Poll a legacy button or mouse click to commit a response. Turn this off " +
                 "if you drive selection from an XR input action and call Select() yourself.")]
        public bool useLegacyInput = true;

        [Tooltip("Legacy button name for the trigger. Left empty, mouse button 0 is used.")]
        public string selectButton = "";

        [Header("Consent and withdrawal")]
        [Tooltip("The consent form itself stays on paper, outside this app.\n\n" +
                 "A VR headset is the wrong place to read a consent form: the participant " +
                 "cannot keep a copy, cannot re-read it later, cannot ask a question " +
                 "without taking the headset off, and a signature captured by a pointer " +
                 "ray is worse evidence than one on paper. What the software owes the " +
                 "ethics record is not the form but a timestamped statement that consent " +
                 "was taken before any stimulus was shown -- which is what this gate is.\n\n" +
                 "OFF by default now that consent is an in-app form shown before the " +
                 "first room: the form writes the audit row from what the participant " +
                 "actually affirmed, which is a better record than a researcher " +
                 "remembering to click a button. Turn it back on to also require a " +
                 "manual confirmation before the session will start at all.")]
        public bool requireConsentConfirmation = false;

        [Tooltip("Version or date of the paper form actually signed. Written to the " +
                 "consent log so a session can be tied to the approved wording.")]
        public string consentFormVersion = "v1";

        [Tooltip("Researcher initials, written alongside the confirmation.")]
        public string researcherInitials = "";

        [Tooltip("Held for withdrawHoldSeconds to end the session early. Held rather " +
                 "than tapped so a stray press cannot end someone's session.")]
        public KeyCode withdrawKey = KeyCode.F12;

        public float withdrawHoldSeconds = 1.5f;

        [Tooltip("File in the persistent data folder recording that consent was taken " +
                 "and whether the session was completed or withdrawn from.")]
        public string consentLogFileName = "consent_log.csv";

        public bool ConsentConfirmed { get; internal set; }
        public bool Withdrawn { get; private set; }

        float withdrawHeldSince = -1f;

        [Header("Session")]
        [Tooltip("The one place the participant id is set. Pushed into TrialRunner, " +
                 "OversightReview, EventLog and StudyTelemetry on wake, so four " +
                 "components cannot disagree about who is in the headset -- which would " +
                 "scatter one person's data across four different ids.")]
        public string participantId = "p01";

        [Tooltip("Start the trial runner automatically. Turn off if a researcher-facing " +
                 "screen starts it, which is usually what you want with a participant present.")]
        public bool autoStart = false;

        [Tooltip("Seconds to wait before auto-starting, so the participant is settled and " +
                 "the headset has finished tracking-init before the first room appears.")]
        public float startDelaySeconds = 3f;

        [Tooltip("Show two unscored warm-up rooms before the first real trial, so the " +
                 "first scored room is not also the first time someone has used the " +
                 "affect grid. Without it the practice effect lands entirely on " +
                 "whichever emotion the counterbalancing put first.")]
        public bool practiceRooms = true;

        [Tooltip("How many real trials a practice run includes, after the warm-up rooms. " +
                 "Enough to meet every question once without spending a participant id.")]
        public int practiceTrialCount = 2;

        [Tooltip("Which halves this participant does.\n\n" +
                 "0 = both (Phase A then Phase B), 1 = Phase A only, 2 = Phase B only.\n\n" +
                 "Phase B is never run first for someone doing both: its attribution " +
                 "question lists all five manipulated variables, so running it first " +
                 "would tell the participant exactly what varies before they rate " +
                 "anything.")]
        public int sessionMode;

        public bool DoesPhaseA { get { return sessionMode != 2; } }
        public bool DoesPhaseB { get { return sessionMode != 1; } }

        [Tooltip("Practice only: run the two warm-up rooms and stop. For piloting the " +
                 "kit and for training a new researcher, without burning a participant " +
                 "id or writing a session that looks real.")]
        public bool practiceOnly = false;

        [Tooltip("Run the oversight review automatically once the eight trials finish. " +
                 "The review must never begin before the main session is complete.")]
        public bool chainOversightBlock = true;

        void Awake()
        {
            ApplyParticipantId();
        }

        /// <summary>Push the id into everything that writes a file.</summary>
        public void ApplyParticipantId()
        {
            if (string.IsNullOrEmpty(participantId)) return;

            if (trialRunner != null)
            {
                trialRunner.participantId = participantId;
                trialRunner.practiceOnly = practiceOnly;
                trialRunner.practiceFileName = practiceRooms ? "practice.json" : "";
            }
            if (oversightReview != null) oversightReview.participantId = participantId;
            if (rationaleReview != null) rationaleReview.participantId = participantId;

            // Found in the scene rather than through TrialRunner, so a log still gets the
            // right id if one of the runners is unwired. A writer that silently keeps the
            // default id is worse than one that is obviously missing.
            foreach (var log in FindObjectsByType<EventLog>(FindObjectsSortMode.None))
                log.participantId = participantId;
            foreach (var log in FindObjectsByType<StudyTelemetry>(FindObjectsSortMode.None))
                log.participantId = participantId;
            if (questionnaires != null)
            {
                questionnaires.participantId = participantId;
                // Null for a participant doing both, so they get every instrument.
                questionnaires.phase = sessionMode == 1 ? "A"
                                     : sessionMode == 2 ? "B" : null;
            }
        }

        void Start()
        {
            // Always chained now: the warm-up hands over to the trials through this.
            if (trialRunner != null) trialRunner.SessionFinished += OnSessionFinished;
            if (oversightReview != null) oversightReview.BlockFinished += OnBlockFinished;
            if (rationaleReview != null) rationaleReview.BlockFinished += OnRationaleFinished;
            if (questionnaires != null) questionnaires.FormFinished += OnFormFinished;

            if (detectionPanel != null) detectionPanel.Answered += OnDetectionAnswered;
            if (attributionPanel != null) attributionPanel.Answered += OnAttributionAnswered;
            if (correctionPanel != null) correctionPanel.Answered += OnCorrectionAnswered;

            if (autoStart) StartCoroutine(AutoStart());
            else ShowIdleState();
        }

        /// <summary>
        /// Say what state the app is in while nothing is running.
        ///
        /// Idle used to show the default skybox and nothing else. Every session in
        /// testing had been started remotely within seconds, so nobody had ever seen the
        /// idle state -- and the first person who did reported it as "endless loading",
        /// which is exactly what an unlabelled empty sky looks like. Ground underfoot and
        /// a sentence naming the state make waiting and broken distinguishable.
        /// </summary>
        void ShowIdleState()
        {
            if (trialRunner != null && trialRunner.loader != null)
                trialRunner.loader.HideRooms();
            if (board != null)
                board.Show("Ready.\n\nStart the session from the laptop:\n" +
                           "Emotion Rooms > Study Control Panel > Start.");
        }

        /// <summary>
        /// Stopping play is a legitimate way to end a session, so it has to leave the
        /// data in the same state a completed run would. Without this, quitting midway
        /// left the per-file CSVs written but no combined file, and the combined file is
        /// the one anybody actually opens.
        /// </summary>
        void OnApplicationQuit()
        {
            if (bundledOnExit) return;
            bundledOnExit = true;

            // Write the file; do NOT abort the runners.
            //
            // Android calls this when the activity is destroyed, which on a Quest happens
            // when the headset is set down mid-session. Aborting here ended the session
            // for a participant who was only adjusting the strap: the room hid, the block
            // stopped, and the screen went empty with nothing to say why. The data up to
            // that point is already on disk either way, so quitting should save and leave
            // the session alone.
            //
            // Through SaveEverything rather than straight to the bundle: quitting used
            // to combine the files without first writing the trial in progress or
            // flushing the buffered logs, so the combined file was built from slightly
            // less than what was known.
            SaveEverything("app closing");
        }

        bool bundledOnExit;
        float lastSaveAt = -999f;

        /// <summary>
        /// Save at every interruption, not only at a clean end.
        ///
        /// The combined file used to be written on OnApplicationQuit, on withdrawal, or
        /// on finishing. Horizon OS does not reliably call OnApplicationQuit -- it kills
        /// the process -- so on a headset that path fires when it feels like it, and the
        /// only reliable writer was a session someone sat all the way through. A session
        /// that ended any other way left no combined file at all.
        ///
        /// Pause is the honest signal. It fires every time the headset leaves someone's
        /// head, which covers a break, a strap adjustment, a participant stopping, the
        /// battery going, and the OS reclaiming the app. Anything that ends a session
        /// ends it through here first.
        ///
        /// Throttled, because pause fires often and a bundle re-reads every response
        /// file. Ten seconds is far below the cost of losing a session and far above the
        /// rate anything changes.
        /// </summary>
        void SaveEverything(string why)
        {
            // Never throttled. These three are cheap and they are the data.
            //
            // The throttle used to sit above this, which made it possible to lose the
            // very thing this method exists to save. Two interruptions inside ten
            // seconds -- a strap adjustment, then the headset coming off for good -- and
            // the second call returned immediately, leaving the trial in progress
            // unwritten and the last rows of the event log sitting in a buffer.
            //
            // The trial in progress goes first, so it is in the responses file before
            // anything reads that file. A session ending here ends mid-trial by
            // definition. The event log and telemetry hold a few rows each, and those
            // rows are what explain a session that stopped.
            if (oversightReview != null) oversightReview.FlushInProgress(why);

            foreach (var log in FindObjectsByType<EventLog>(FindObjectsSortMode.None))
                log.Flush();
            foreach (var stream in FindObjectsByType<StudyTelemetry>(FindObjectsSortMode.None))
                stream.Flush();

            // Throttled. This re-reads every response file and rewrites the combined
            // one, and running it twice in a second produces the same file. If it is
            // skipped, every row it would have gathered is already on disk in the files
            // it gathers from, and bundle-participant rebuilds it offline.
            if (Time.realtimeSinceStartup - lastSaveAt < 10f) return;
            lastSaveAt = Time.realtimeSinceStartup;
            BundleNow(why);
        }

        void OnApplicationPause(bool paused)
        {
            if (paused) SaveEverything("headset set down or app paused");
        }

        void OnApplicationFocus(bool focused)
        {
            if (!focused) SaveEverything("app lost focus");
        }

        void OnDestroy()
        {
            if (trialRunner != null) trialRunner.SessionFinished -= OnSessionFinished;
            if (oversightReview != null) oversightReview.BlockFinished -= OnBlockFinished;
            if (rationaleReview != null) rationaleReview.BlockFinished -= OnRationaleFinished;
            if (questionnaires != null) questionnaires.FormFinished -= OnFormFinished;
            if (detectionPanel != null) detectionPanel.Answered -= OnDetectionAnswered;
            if (attributionPanel != null) attributionPanel.Answered -= OnAttributionAnswered;
            if (correctionPanel != null) correctionPanel.Answered -= OnCorrectionAnswered;
        }

        IEnumerator AutoStart()
        {
            yield return new WaitForSeconds(startDelaySeconds);
            BeginStudy();
        }

        /// <summary>Start the main session. Safe to call from a UI button.</summary>
        [ContextMenu("Begin Study")]
        public void BeginStudy()
        {
            if (trialRunner == null)
            {
                Debug.LogError("StudyBootstrap: no TrialRunner assigned.");
                return;
            }
            if (requireConsentConfirmation && !ConsentConfirmed)
            {
                Debug.LogError("StudyBootstrap: consent has not been confirmed, so the " +
                               "session will not start. Take the paper consent form, then " +
                               "use Emotion Rooms > Confirm Consent Taken (or the " +
                               "component's context menu).");
                return;
            }
            if (Withdrawn)
            {
                Debug.LogWarning("StudyBootstrap: this participant withdrew. Restart the " +
                                 "scene with a new participant id rather than resuming.");
                return;
            }
            ApplyParticipantId();

            // Straight into the rooms. The before-forms are browser pages the researcher
            // opens while the headset is still off, so the app has nothing to wait for --
            // and a session that waited on a form would be a session a skipped form could
            // stall.
            // Fetch this participant's rooms first if they are not in memory yet. They
            // are loaded on demand rather than at startup, so pressing Begin is the first
            // moment we know which three files are actually needed.
            if (!ShippedAssets.HasParticipant(participantId) &&
                ShippedAssets.Instance != null)
            {
                StartCoroutine(BeginWhenRoomsLoaded());
                return;
            }

            StartPhases();
        }

        System.Collections.IEnumerator BeginWhenRoomsLoaded()
        {
            if (board != null) board.Show("Just a moment…");
            yield return ShippedAssets.Instance.LoadParticipant(participantId);

            // Any id resolves to one of the shipped counterbalancing orders, so the only
            // way to get here empty is a build with no packs at all.
            if (!ShippedAssets.HasParticipant(participantId) &&
                !System.IO.File.Exists(System.IO.Path.Combine(
                    Application.persistentDataPath, "session.json")))
            {
                string message = "This build has no rooms in it.\n\n" +
                                 "Rebuild and reinstall from the laptop.";
                if (board != null) board.Show(message);
                Debug.LogError("StudyBootstrap: " + message.Replace("\n", " "));
                RoomsMissing = true;
                yield break;
            }

            // Which order this participant saw. The id is theirs; the order is one of
            // thirty, and analysis needs to know which without anyone writing it down.
            if (trialRunner != null && trialRunner.events != null)
                trialRunner.events.WriteValues("counterbalance_order",
                    participantId, ParticipantPacks.PackFor(participantId), null);

            RoomsMissing = false;
            StartPhases();
        }

        /// <summary>Set when the last Begin found no rooms, so the panel can say so.</summary>
        public bool RoomsMissing { get; private set; }

        void StartPhases()
        {
            if (board != null) board.Hide();

            // One trial format for the whole session (design-unified.md). There is no
            // separate 8-room affect phase any more: every one of the 32 trials starts
            // with the affect grid, and the thesis measure is that grid on the 16
            // faithful trials - the model's own output for each emotion, seen twice per
            // shape. Corrupted trials are excluded from that analysis because they are
            // not the model's output for the stated emotion.
            //
            // The warm-up still runs first, in the same trial format, so nobody meets
            // the grid for the first time on a scored trial. practiceOnly stops there.
            if (trialRunner != null && practiceRooms)
            {
                // Practice goes on into the block too, just a short way in. A
                // rehearsal that stops before the questions rehearses nothing that
                // matters, and it is the questions a pilot needs to check.
                runBlockAfterPractice = true;
                if (oversightReview != null)
                    oversightReview.trialLimit = practiceOnly ? practiceTrialCount : 0;
                trialRunner.practiceOnly = true;   // warm-up only; the block follows
                trialRunner.BeginSession();
                return;                            // OnSessionFinished starts the block
            }

            BeginReviewBlock();
        }

        void BeginReviewBlock()
        {
            if (oversightReview != null) oversightReview.BeginBlock();
            else Debug.LogError("StudyBootstrap: no OversightReview, so the session has " +
                                "nothing to run.");
        }

        /// <summary>
        /// The consent form writes the audit row itself, so the ethics record follows
        /// what the participant actually agreed to rather than what a researcher
        /// remembered to click.
        ///
        /// A session where consent was skipped or left partial still proceeds -- nothing
        /// here blocks -- but it is written as `consent_incomplete`, the end screen names
        /// it, and the bundle reports the session as not usable. That is deliberate: the
        /// record should be loud rather than the door being locked.
        /// </summary>
        void OnFormFinished(string formId, FormState state)
        {
            if (formId != "consent") return;

            if (questionnaires.ConsentAffirmed())
            {
                ConsentConfirmed = true;
                WriteConsentRow("consent_taken", "in_app_form");
            }
            else
            {
                WriteConsentRow("consent_incomplete", state.ToString());
                Debug.LogWarning("StudyBootstrap: consent was not fully affirmed (" + state +
                                 "). The session will continue and the gap is recorded, but " +
                                 "this participant's data is not usable until consent is " +
                                 "taken on paper and noted.");
            }
        }

        /// <summary>
        /// Record that the paper consent form was completed. Researcher action, taken
        /// with the headset still off.
        /// </summary>
        [ContextMenu("Confirm Consent Taken")]
        public void ConfirmConsentTaken()
        {
            if (ConsentConfirmed) return;
            ConsentConfirmed = true;
            WriteConsentRow("consent_taken", "");
            if (trialRunner != null && trialRunner.events != null)
                trialRunner.events.WriteValues("session_mode",
                    sessionMode == 1 ? "phase_a_only"
                    : sessionMode == 2 ? "phase_b_only" : "both",
                    practiceOnly ? "practice" : "real", null);
            if (trialRunner != null && trialRunner.events != null)
                trialRunner.events.WriteValues("consent_confirmed", consentFormVersion,
                    researcherInitials, null);
            Debug.Log("StudyBootstrap: consent recorded for " + ParticipantId() +
                      ". Safe to begin.");
        }

        /// <summary>
        /// End the session early at the participant's request. Everything recorded so far
        /// is kept and marked; nothing is deleted here, because whether a partial session
        /// is usable is an analysis decision and destroying the data pre-empts it. If the
        /// participant asks for their data to be destroyed, that is a separate, deliberate
        /// act on the files themselves.
        /// </summary>
        [ContextMenu("Withdraw Participant")]
        public void WithdrawParticipant()
        {
            if (Withdrawn) return;
            Withdrawn = true;

            if (trialRunner != null) trialRunner.Abort("participant_withdrew");
            if (oversightReview != null) oversightReview.Abort("participant_withdrew");
            if (grid != null) grid.Hide();
            if (detectionPanel != null) detectionPanel.Hide();
            if (attributionPanel != null) attributionPanel.Hide();
            if (correctionPanel != null) correctionPanel.Hide();

            if (questionnaires != null) questionnaires.ShowSummary();
            WriteConsentRow("withdrawn", CompletedSoFar());
            BundleNow("participant withdrew");
            Debug.LogWarning("StudyBootstrap: participant withdrew. Take the headset off, " +
                             "debrief, and note the reason on the paper record.");
        }

        string ParticipantId()
        {
            if (trialRunner != null && !string.IsNullOrEmpty(trialRunner.participantId))
                return trialRunner.participantId;
            if (oversightReview != null) return oversightReview.participantId;
            return "unknown";
        }

        string CompletedSoFar()
        {
            return trialRunner == null
                ? ""
                : trialRunner.CompletedTrials.ToString(CultureInfo.InvariantCulture);
        }

        void WriteConsentRow(string eventName, string detail)
        {
            string path = Path.Combine(Application.persistentDataPath, consentLogFileName);
            try
            {
                if (!File.Exists(path))
                {
                    File.WriteAllText(path,
                        "participant,event,utc,consent_form_version,researcher,detail\n",
                        Encoding.UTF8);
                }
                File.AppendAllText(path, string.Join(",", new[]
                {
                    ParticipantId(),
                    eventName,
                    DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture),
                    consentFormVersion,
                    researcherInitials,
                    detail ?? "",
                }) + "\n", Encoding.UTF8);
            }
            catch (IOException e)
            {
                // Never take the session down over the audit file. The event log carries
                // the same fact and the paper form is the actual record.
                Debug.LogError("StudyBootstrap: could not write " + path + ": " + e.Message);
            }
        }

        void OnSessionFinished()
        {
            // Reached when the warm-up ends. A pilot asked for practice only stops
            // here; everyone else goes straight into the 32 unified trials, which is
            // the whole session under design-unified.md.
            practiceOnly = false;
            Debug.Log("StudyBootstrap: warm-up finished, starting the trials.");
            BeginReviewBlock();
        }

        /// <summary>
        /// True for a real session: the warm-up is a prelude, not the session. False
        /// when the researcher asked for practice only, which is the pilot path.
        /// </summary>
        bool runBlockAfterPractice;

        void OnBlockFinished()
        {
            // No separate rationale block any more. It asked whether the stated
            // reasoning matched the room; the main trials now show that reasoning on
            // half of themselves and ask a sharper question about it, so a tail block
            // repeating it costs minutes the session does not have. RationaleReview is
            // still wired and still runs if a block file is present, which is what the
            // pilot path uses.
            if (rationaleReview != null && rationaleReview.HasBlockFile)
            {
                rationaleReview.BeginBlock();
                return;
            }
            OnRationaleFinished();
        }

        void OnRationaleFinished()
        {
            // The VR part is over. The after-forms are opened from the panel once the
            // headset is off -- NASA-TLX asks about the review block, so it wants to be
            // soon, but it does not want to be answered through a headset.
            if (questionnaires != null) questionnaires.ShowSummary();
            if (board != null)
                board.Show("That is everything.\n\nPlease take the headset off.");
            BundleNow("rooms and review finished");
        }

        /// <summary>Write the combined CSV. Runs itself, so nobody has to remember to.</summary>
        void BundleNow(string why)
        {
            string path = SessionBundle.Write(participantId);
            if (path == null)
            {
                Debug.LogWarning("StudyBootstrap: " + why + " for " + participantId +
                                 ", but there was nothing to bundle.");
                return;
            }
            Debug.Log("StudyBootstrap: " + why + " for " + participantId +
                      ". Everything combined into:\n  " + path);
        }

        void OnDetectionAnswered(string value, float confidence)
        {
            // The same two-option panel serves both blocks; whichever is running owns it.
            if (rationaleReview != null && rationaleReview.IsRunning)
            {
                rationaleReview.CommitAnswer(value == "yes");
                return;
            }
            if (oversightReview == null) return;

            // The same two-option panel serves the reasoning-match question and the
            // room-alteration question; whichever is on screen owns the answer.
            if (oversightReview.AwaitingExplanationMatch)
            {
                oversightReview.pendingExplanationConfidence = confidence;
                oversightReview.CommitExplanationMatch(value == "yes");
                return;
            }

            oversightReview.pendingDetectionConfidence = confidence;
            // POLARITY INVARIANT: the detection question asks whether the room HAS BEEN
            // CHANGED, so yes means detected. This line once read yes -> false -- the
            // wording and the mapping had drifted apart -- and every detection in the
            // block would have been recorded inverted: d-prime negative, hits counted
            // as misses, an entire phase poisoned silently. If the question wording in
            // OversightReview.RunBlock ever changes, this mapping changes with it.
            oversightReview.CommitDetection(value == "yes");
        }

        void OnAttributionAnswered(string value, float confidence)
        {
            if (oversightReview == null) return;
            oversightReview.pendingAttributionConfidence = confidence;
            oversightReview.CommitAttribution(value);
        }

        void OnCorrectionAnswered(string value, float confidence)
        {
            if (oversightReview != null) oversightReview.CommitCorrection(value);
        }

        /// <summary>The panel currently awaiting an answer, for the remote instrument.</summary>
        public QuestionPanel CurrentPanel()
        {
            return ActivePanel();
        }

        QuestionPanel ActivePanel()
        {
            if (detectionPanel != null && detectionPanel.IsAwaitingAnswer) return detectionPanel;
            if (attributionPanel != null && attributionPanel.IsAwaitingAnswer) return attributionPanel;
            if (correctionPanel != null && correctionPanel.IsAwaitingAnswer) return correctionPanel;
            return null;
        }

        void Update()
        {
            PollWithdrawal();
            PollController();

            // Read each hand's trigger edge exactly once per frame. Both hands carry a
            // ray now, and a press has to commit with the ray of the hand that pressed:
            // one shared "any trigger" bit either loses that or eats the edge twice.
            bool xr = xrRig != null && xrRig.HeadsetPresent;
            Ray rightRay = default(Ray), leftRay = default(Ray), mouseRay = default(Ray);
            bool haveRight = xr && HandRay(xrRig.pointer, out rightRay);
            bool haveLeft = xr && HandRay(xrRig.leftPointer, out leftRay);
            bool rightDown = useLegacyInput && haveRight && XRRig.TriggerPressed(UnityEngine.XR.XRNode.RightHand);
            bool leftDown = useLegacyInput && haveLeft && XRRig.TriggerPressed(UnityEngine.XR.XRNode.LeftHand);
            bool haveMouse = !xr && MouseRay(out mouseRay);
            bool mouseDown = useLegacyInput && haveMouse && Input.GetMouseButtonDown(0);

            if (pilotMode && PumpSkipButton(rightDown, rightRay, leftDown, leftRay,
                                            mouseDown, mouseRay)) return;

            // Raw input stream, decided 8 Aug 2026: every press is a row no matter how
            // often it repeats or whether it landed. What people pressed at and missed
            // is data the successful-selection rows silently discard.
            if (events != null)
            {
                if (rightDown) LogPress("right", rightRay);
                if (leftDown) LogPress("left", leftRay);
                if (mouseDown) LogPress("mouse", mouseRay);
            }

            var panel = ActivePanel();
            if (panel != null)
            {
                // Ray and trigger only, decided 8 Aug 2026. Face buttons answered
                // yes/no directly, which resolved the panel before the confidence strip
                // could be touched -- and one input grammar for everything (point,
                // squeeze) is easier to brief than two.
                if (haveRight) panel.Hover(rightRay);
                if (haveLeft) panel.Hover(leftRay);
                if (haveMouse) panel.Hover(mouseRay);

                if (rightDown) panel.TrySelect(rightRay);
                else if (leftDown) panel.TrySelect(leftRay);
                else if (mouseDown) panel.TrySelect(mouseRay);
                return;
            }

            if (grid == null || !grid.IsAwaitingResponse) return;

            if (haveRight) grid.Hover(rightRay);
            if (haveLeft) grid.Hover(leftRay);
            if (haveMouse) grid.Hover(mouseRay);

            AffectResponse response;
            if (rightDown) grid.TrySelect(rightRay, out response);
            else if (leftDown) grid.TrySelect(leftRay, out response);
            else if (mouseDown) grid.TrySelect(mouseRay, out response);
        }

        Transform skipButton;
        Collider skipArea;

        /// <summary>
        /// The pilot skip control: overhead, out of every normal sightline, present only
        /// while a part is running and only in pilot mode. Built at runtime like every
        /// other interactive object -- nothing new is serialized into the scene.
        /// </summary>
        bool PumpSkipButton(bool rightDown, Ray rightRay, bool leftDown, Ray leftRay,
                            bool mouseDown, Ray mouseRay)
        {
            bool active = (trialRunner != null && trialRunner.IsRunning) ||
                          (oversightReview != null && oversightReview.IsRunning) ||
                          (rationaleReview != null && rationaleReview.IsRunning);

            if (skipButton == null && active) BuildSkipButton();
            if (skipButton == null) return false;
            if (skipButton.gameObject.activeSelf != active)
                skipButton.gameObject.SetActive(active);
            if (!active || skipArea == null) return false;

            RaycastHit hit;
            if (rightDown && skipArea.Raycast(rightRay, out hit, 100f)) return SkipActivePart();
            if (leftDown && skipArea.Raycast(leftRay, out hit, 100f)) return SkipActivePart();
            if (mouseDown && skipArea.Raycast(mouseRay, out hit, 100f)) return SkipActivePart();
            return false;
        }

        void BuildSkipButton()
        {
            var anchor = xrRig != null && xrRig.Origin != null ? xrRig.Origin.position : Vector3.zero;

            var slab = WorldLabel.Solid("Cube.fbx", "Pilot Skip Button", null);
            // High and off to the right, not straight ahead. Centred above the panels
            // it overlapped the question text, which is the one thing on screen that
            // must never be obscured. Out here it takes a deliberate look up and right.
            slab.transform.position = anchor + new Vector3(1.15f, 2.35f, 1.1f);
            slab.transform.rotation = Quaternion.LookRotation(
                (slab.transform.position - (anchor + Vector3.up * 1.6f)).normalized);
            slab.transform.localScale = new Vector3(0.6f, 0.16f, 0.02f);

            var box = slab.AddComponent<BoxCollider>();
            box.isTrigger = true;
            skipArea = box;

            var renderer = slab.GetComponent<Renderer>();
            var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            if (renderer != null && shader != null)
                renderer.material = new Material(shader) { color = new Color(0.45f, 0.16f, 0.16f) };

            var text = new GameObject("Pilot Skip Label").transform;
            text.SetParent(slab.transform.parent, false);
            text.position = slab.transform.position + slab.transform.rotation * new Vector3(0f, 0f, -0.02f);
            text.rotation = slab.transform.rotation;
            WorldLabel.Attach(text, "SKIP THIS PART (pilot)", 0.06f, Vector3.zero,
                              TextAnchor.MiddleCenter);
            text.SetParent(slab.transform, true);

            skipButton = slab.transform;
        }

        float skipArmedAt = -999f;

        /// <summary>
        /// Skip the running part. Two presses, because one press ends a block.
        ///
        /// This slab sits high and to the right so it takes a deliberate look to reach.
        /// That stopped being true the moment the eye-height bug lifted the viewpoint by
        /// 1.2 m: the button is at 2.35 m and the participant's head went to about 2.4 m,
        /// which put it straight down the middle of where they were looking. One stray
        /// trigger press ended the whole review block, and from the inside it simply
        /// looked like the study finishing after the familiarisation rooms.
        ///
        /// The height bug is fixed. This is the second lock, because the cost of an
        /// accidental press is an entire session and the cost of a deliberate one is
        /// pressing twice.
        /// </summary>
        bool SkipActivePart()
        {
            if (events != null) events.Write("pilot_skip_pressed", null);

            if (Time.time - skipArmedAt > 4f)
            {
                skipArmedAt = Time.time;
                if (board != null)
                    board.Show("Skip this part?\n\nPress the button again to skip.\n" +
                               "Do nothing and this goes away.");
                if (events != null) events.Write("pilot_skip_armed", null);
                return true;
            }

            skipArmedAt = -999f;
            if (board != null) board.Hide();
            if (events != null) events.Write("phase_skipped", null);

            if (trialRunner != null && trialRunner.IsRunning) trialRunner.SkipSession();
            else if (oversightReview != null && oversightReview.IsRunning) oversightReview.SkipBlock();
            else if (rationaleReview != null && rationaleReview.IsRunning) rationaleReview.SkipBlock();
            return true;
        }

        void LogPress(string hand, Ray ray)
        {
            string hit = "nothing";
            RaycastHit info;
            if (Physics.Raycast(ray, out info, 100f, ~0, QueryTriggerInteraction.Collide))
                hit = info.transform.name;
            var row = hand + " from " + ray.origin.ToString("F3") +
                      " dir " + ray.direction.ToString("F3");
            if (xrRig != null) xrRig.NoteInput();
            events.WriteValues("trigger_press", hand, hit, row);
        }

        static bool HandRay(Transform hand, out Ray ray)
        {
            ray = default(Ray);
            if (hand == null) return false;
            ray = new Ray(hand.position, hand.forward);
            return true;
        }

        bool MouseRay(out Ray ray)
        {
            ray = default(Ray);
            var camera = fallbackCamera != null ? fallbackCamera : Camera.main;
            if (camera == null) return false;
            ray = camera.ScreenPointToRay(Input.mousePosition);
            return true;
        }

        bool warnedNoController;

        /// <summary>
        /// Keep telling the truth about the controller.
        ///
        /// Checked once at Begin, this said "no controller detected" and then never took
        /// it back -- so a controller that woke a second later left the message on screen
        /// while the pointer worked perfectly. Re-evaluated every frame, the message
        /// appears when a controller really is missing and clears the moment one reports.
        /// </summary>
        string interruptedBoardText;

        void PollController()
        {
            if (xrRig == null || board == null || !xrRig.HeadsetPresent) return;

            bool tracked = xrRig.ControllerTracked();
            if (!tracked && !warnedNoController)
            {
                // Put back whatever was there afterwards.
                //
                // This warning borrows the one board the study also uses for the
                // briefing, the familiarisation labels and the system's stated
                // reasoning. It used to clear itself with a plain Hide(), so a
                // controller that dropped out for a moment during the briefing took the
                // briefing with it and nothing brought it back: the participant was left
                // in a room with no instructions and no way to ask for them.
                //
                // A controller dropping out is also the most likely moment for exactly
                // that, because it happens while somebody is sitting still reading.
                interruptedBoardText = board.Current;
                warnedNoController = true;
                board.Show("No controller detected.\n\nPick one up and squeeze the " +
                           "trigger. A blue beam will appear.");
            }
            else if (tracked && warnedNoController)
            {
                warnedNoController = false;
                if (!string.IsNullOrEmpty(interruptedBoardText))
                    board.Show(interruptedBoardText);
                else
                    board.Hide();
                interruptedBoardText = null;
            }
        }

        void PollWithdrawal()
        {
            if (Withdrawn || withdrawKey == KeyCode.None) return;

            if (!Input.GetKey(withdrawKey))
            {
                withdrawHeldSince = -1f;
                return;
            }

            if (withdrawHeldSince < 0f) withdrawHeldSince = Time.unscaledTime;
            else if (Time.unscaledTime - withdrawHeldSince >= withdrawHoldSeconds)
                WithdrawParticipant();
        }

    }
}
