// Starts the session and drives pointer input into the affect grid.
//
// AffectGrid exposes Hover() and TrySelect() but deliberately does not read input
// itself: what counts as "pointing" differs between a controller ray, a gaze cursor and
// a mouse in the editor, and burying one of those inside the instrument would make the
// other two awkward. This is the piece that decides.
//
// Attach to one GameObject in the scene and wire the three references. Nothing else in
// the study needs an input dependency.
//
// Editor testing works out of the box with the mouse. For the headset, point
// `pointerOrigin` at your controller's ray transform and call Select() from whatever
// input system you use, or leave `useLegacyInput` on if your rig maps the trigger to a
// legacy button.

using System;
using System.Collections;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;

namespace EmotionRooms
{
    public class StudyBootstrap : MonoBehaviour
    {
        [Header("Wiring")]
        public TrialRunner trialRunner;
        public OversightReview oversightReview;
        public AffectGrid grid;

        [Tooltip("In-app forms. Runs the 'before' set on Begin Study and the 'after' set " +
                 "once the review block ends. Never blocks: every form can be skipped.")]
        public QuestionnaireRunner questionnaires;

        [Tooltip("World-space text, so the participant can be told something in VR. " +
                 "IMGUI does not render into an immersive view.")]
        public MessageBoard board;

        [Header("Review panels")]
        [Tooltip("Generated by Emotion Rooms > Set Up Study Scene. Without these the " +
                 "review block waits forever for an answer that can never arrive.")]
        public QuestionPanel detectionPanel;
        public QuestionPanel attributionPanel;
        public QuestionPanel correctionPanel;

        [Tooltip("Head and controller tracking on the headset. Inert with no headset, " +
                 "so the same scene still runs on a laptop with a mouse.")]
        public XRRig xrRig;

        [Header("Pointer")]
        [Tooltip("Transform whose forward axis is the pointing ray. A controller's ray " +
                 "origin in the headset. Leave empty in the editor and the mouse is used.")]
        public Transform pointerOrigin;

        [Tooltip("Camera used to build the ray when pointerOrigin is empty. Defaults to " +
                 "Camera.main.")]
        public Camera fallbackCamera;

        [Header("Input")]
        [Tooltip("Poll a legacy button or mouse click to commit a response. Turn this off " +
                 "if you drive selection from an XR input action and call Select() yourself.")]
        public bool useLegacyInput = true;

        [Tooltip("Legacy button name for the trigger. Left empty, mouse button 0 is used.")]
        public string selectButton = "";

        [Header("Consent and withdrawal")]
        [Tooltip("The consent form itself stays on paper, outside this app.\n\n" +
                 "A VR headset is the wrong place to read a consent form: the participant " +
                 "cannot keep a copy, cannot re-read it later, cannot ask a question " +
                 "without taking the headset off, and a signature captured by a pointer " +
                 "ray is worse evidence than one on paper. What the software owes the " +
                 "ethics record is not the form but a timestamped statement that consent " +
                 "was taken before any stimulus was shown -- which is what this gate is.\n\n" +
                 "OFF by default now that consent is an in-app form shown before the " +
                 "first room: the form writes the audit row from what the participant " +
                 "actually affirmed, which is a better record than a researcher " +
                 "remembering to click a button. Turn it back on to also require a " +
                 "manual confirmation before the session will start at all.")]
        public bool requireConsentConfirmation = false;

        [Tooltip("Version or date of the paper form actually signed. Written to the " +
                 "consent log so a session can be tied to the approved wording.")]
        public string consentFormVersion = "v1";

        [Tooltip("Researcher initials, written alongside the confirmation.")]
        public string researcherInitials = "";

        [Tooltip("Held for withdrawHoldSeconds to end the session early. Held rather " +
                 "than tapped so a stray press cannot end someone's session.")]
        public KeyCode withdrawKey = KeyCode.F12;

        public float withdrawHoldSeconds = 1.5f;

        [Tooltip("File in the persistent data folder recording that consent was taken " +
                 "and whether the session was completed or withdrawn from.")]
        public string consentLogFileName = "consent_log.csv";

        public bool ConsentConfirmed { get; internal set; }
        public bool Withdrawn { get; private set; }

        float withdrawHeldSince = -1f;

        [Header("Session")]
        [Tooltip("The one place the participant id is set. Pushed into TrialRunner, " +
                 "OversightReview, EventLog and StudyTelemetry on wake, so four " +
                 "components cannot disagree about who is in the headset -- which would " +
                 "scatter one person's data across four different ids.")]
        public string participantId = "p01";

        [Tooltip("Start the trial runner automatically. Turn off if a researcher-facing " +
                 "screen starts it, which is usually what you want with a participant present.")]
        public bool autoStart = false;

        [Tooltip("Seconds to wait before auto-starting, so the participant is settled and " +
                 "the headset has finished tracking-init before the first room appears.")]
        public float startDelaySeconds = 3f;

        [Tooltip("Show two unscored warm-up rooms before the first real trial, so the " +
                 "first scored room is not also the first time someone has used the " +
                 "affect grid. Without it the practice effect lands entirely on " +
                 "whichever emotion the counterbalancing put first.")]
        public bool practiceRooms = true;

        [Tooltip("Which halves this participant does.\n\n" +
                 "0 = both (Phase A then Phase B), 1 = Phase A only, 2 = Phase B only.\n\n" +
                 "Phase B is never run first for someone doing both: its attribution " +
                 "question lists all five manipulated variables, so running it first " +
                 "would tell the participant exactly what varies before they rate " +
                 "anything.")]
        public int sessionMode;

        public bool DoesPhaseA { get { return sessionMode != 2; } }
        public bool DoesPhaseB { get { return sessionMode != 1; } }

        [Tooltip("Practice only: run the two warm-up rooms and stop. For piloting the " +
                 "kit and for training a new researcher, without burning a participant " +
                 "id or writing a session that looks real.")]
        public bool practiceOnly = false;

        [Tooltip("Run the oversight review automatically once the eight trials finish. " +
                 "The review must never begin before the main session is complete.")]
        public bool chainOversightBlock = true;

        void Awake()
        {
            ApplyParticipantId();
        }

        /// <summary>Push the id into everything that writes a file.</summary>
        public void ApplyParticipantId()
        {
            if (string.IsNullOrEmpty(participantId)) return;

            if (trialRunner != null)
            {
                trialRunner.participantId = participantId;
                trialRunner.practiceOnly = practiceOnly;
                trialRunner.practiceFileName = practiceRooms ? "practice.json" : "";
            }
            if (oversightReview != null) oversightReview.participantId = participantId;

            // Found in the scene rather than through TrialRunner, so a log still gets the
            // right id if one of the runners is unwired. A writer that silently keeps the
            // default id is worse than one that is obviously missing.
            foreach (var log in FindObjectsByType<EventLog>(FindObjectsSortMode.None))
                log.participantId = participantId;
            foreach (var log in FindObjectsByType<StudyTelemetry>(FindObjectsSortMode.None))
                log.participantId = participantId;
            if (questionnaires != null) questionnaires.participantId = participantId;
        }

        void Start()
        {
            if (trialRunner != null && chainOversightBlock && oversightReview != null)
            {
                trialRunner.SessionFinished += OnSessionFinished;
            }
            if (oversightReview != null) oversightReview.BlockFinished += OnBlockFinished;
            if (questionnaires != null) questionnaires.FormFinished += OnFormFinished;

            if (detectionPanel != null) detectionPanel.Answered += OnDetectionAnswered;
            if (attributionPanel != null) attributionPanel.Answered += OnAttributionAnswered;
            if (correctionPanel != null) correctionPanel.Answered += OnCorrectionAnswered;

            if (autoStart) StartCoroutine(AutoStart());
        }

        /// <summary>
        /// Stopping play is a legitimate way to end a session, so it has to leave the
        /// data in the same state a completed run would. Without this, quitting midway
        /// left the per-file CSVs written but no combined file, and the combined file is
        /// the one anybody actually opens.
        /// </summary>
        void OnApplicationQuit()
        {
            if (bundledOnExit) return;
            bundledOnExit = true;

            if (trialRunner != null && trialRunner.IsRunning)
                trialRunner.Abort("stopped_early");
            if (oversightReview != null && oversightReview.IsRunning)
                oversightReview.Abort("stopped_early");

            BundleNow("session stopped early");
        }

        bool bundledOnExit;

        void OnDestroy()
        {
            if (trialRunner != null) trialRunner.SessionFinished -= OnSessionFinished;
            if (oversightReview != null) oversightReview.BlockFinished -= OnBlockFinished;
            if (questionnaires != null) questionnaires.FormFinished -= OnFormFinished;
            if (detectionPanel != null) detectionPanel.Answered -= OnDetectionAnswered;
            if (attributionPanel != null) attributionPanel.Answered -= OnAttributionAnswered;
            if (correctionPanel != null) correctionPanel.Answered -= OnCorrectionAnswered;
        }

        IEnumerator AutoStart()
        {
            yield return new WaitForSeconds(startDelaySeconds);
            BeginStudy();
        }

        /// <summary>Start the main session. Safe to call from a UI button.</summary>
        [ContextMenu("Begin Study")]
        public void BeginStudy()
        {
            if (trialRunner == null)
            {
                Debug.LogError("StudyBootstrap: no TrialRunner assigned.");
                return;
            }
            if (requireConsentConfirmation && !ConsentConfirmed)
            {
                Debug.LogError("StudyBootstrap: consent has not been confirmed, so the " +
                               "session will not start. Take the paper consent form, then " +
                               "use Emotion Rooms > Confirm Consent Taken (or the " +
                               "component's context menu).");
                return;
            }
            if (Withdrawn)
            {
                Debug.LogWarning("StudyBootstrap: this participant withdrew. Restart the " +
                                 "scene with a new participant id rather than resuming.");
                return;
            }
            ApplyParticipantId();

            // Straight into the rooms. The before-forms are browser pages the researcher
            // opens while the headset is still off, so the app has nothing to wait for --
            // and a session that waited on a form would be a session a skipped form could
            // stall.
            if (board != null) board.Hide();

            if (!DoesPhaseA)
            {
                // Phase B only. The cleanest version of the oversight study: no prior
                // exposure to the rooms, so a faithful stimulus is no more familiar than
                // a random one, and nothing has told them what varies.
                if (oversightReview != null) oversightReview.BeginBlock();
                else Debug.LogError("StudyBootstrap: Phase B only, but no OversightReview.");
                return;
            }

            trialRunner.BeginSession();
        }

        /// <summary>
        /// The consent form writes the audit row itself, so the ethics record follows
        /// what the participant actually agreed to rather than what a researcher
        /// remembered to click.
        ///
        /// A session where consent was skipped or left partial still proceeds -- nothing
        /// here blocks -- but it is written as `consent_incomplete`, the end screen names
        /// it, and the bundle reports the session as not usable. That is deliberate: the
        /// record should be loud rather than the door being locked.
        /// </summary>
        void OnFormFinished(string formId, FormState state)
        {
            if (formId != "consent") return;

            if (questionnaires.ConsentAffirmed())
            {
                ConsentConfirmed = true;
                WriteConsentRow("consent_taken", "in_app_form");
            }
            else
            {
                WriteConsentRow("consent_incomplete", state.ToString());
                Debug.LogWarning("StudyBootstrap: consent was not fully affirmed (" + state +
                                 "). The session will continue and the gap is recorded, but " +
                                 "this participant's data is not usable until consent is " +
                                 "taken on paper and noted.");
            }
        }

        /// <summary>
        /// Record that the paper consent form was completed. Researcher action, taken
        /// with the headset still off.
        /// </summary>
        [ContextMenu("Confirm Consent Taken")]
        public void ConfirmConsentTaken()
        {
            if (ConsentConfirmed) return;
            ConsentConfirmed = true;
            WriteConsentRow("consent_taken", "");
            if (trialRunner != null && trialRunner.events != null)
                trialRunner.events.WriteValues("session_mode",
                    sessionMode == 1 ? "phase_a_only"
                    : sessionMode == 2 ? "phase_b_only" : "both",
                    practiceOnly ? "practice" : "real", null);
            if (trialRunner != null && trialRunner.events != null)
                trialRunner.events.WriteValues("consent_confirmed", consentFormVersion,
                    researcherInitials, null);
            Debug.Log("StudyBootstrap: consent recorded for " + ParticipantId() +
                      ". Safe to begin.");
        }

        /// <summary>
        /// End the session early at the participant's request. Everything recorded so far
        /// is kept and marked; nothing is deleted here, because whether a partial session
        /// is usable is an analysis decision and destroying the data pre-empts it. If the
        /// participant asks for their data to be destroyed, that is a separate, deliberate
        /// act on the files themselves.
        /// </summary>
        [ContextMenu("Withdraw Participant")]
        public void WithdrawParticipant()
        {
            if (Withdrawn) return;
            Withdrawn = true;

            if (trialRunner != null) trialRunner.Abort("participant_withdrew");
            if (oversightReview != null) oversightReview.Abort("participant_withdrew");
            if (grid != null) grid.Hide();
            if (detectionPanel != null) detectionPanel.Hide();
            if (attributionPanel != null) attributionPanel.Hide();
            if (correctionPanel != null) correctionPanel.Hide();

            if (questionnaires != null) questionnaires.ShowSummary();
            WriteConsentRow("withdrawn", CompletedSoFar());
            BundleNow("participant withdrew");
            Debug.LogWarning("StudyBootstrap: participant withdrew. Take the headset off, " +
                             "debrief, and note the reason on the paper record.");
        }

        string ParticipantId()
        {
            if (trialRunner != null && !string.IsNullOrEmpty(trialRunner.participantId))
                return trialRunner.participantId;
            if (oversightReview != null) return oversightReview.participantId;
            return "unknown";
        }

        string CompletedSoFar()
        {
            return trialRunner == null
                ? ""
                : trialRunner.CompletedTrials.ToString(CultureInfo.InvariantCulture);
        }

        void WriteConsentRow(string eventName, string detail)
        {
            string path = Path.Combine(Application.persistentDataPath, consentLogFileName);
            try
            {
                if (!File.Exists(path))
                {
                    File.WriteAllText(path,
                        "participant,event,utc,consent_form_version,researcher,detail\n",
                        Encoding.UTF8);
                }
                File.AppendAllText(path, string.Join(",", new[]
                {
                    ParticipantId(),
                    eventName,
                    DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture),
                    consentFormVersion,
                    researcherInitials,
                    detail ?? "",
                }) + "\n", Encoding.UTF8);
            }
            catch (IOException e)
            {
                // Never take the session down over the audit file. The event log carries
                // the same fact and the paper form is the actual record.
                Debug.LogError("StudyBootstrap: could not write " + path + ": " + e.Message);
            }
        }

        void OnSessionFinished()
        {
            if (practiceOnly)
            {
                Debug.Log("StudyBootstrap: practice run finished. Nothing was scored and " +
                          "the review block was skipped.");
                if (questionnaires != null) questionnaires.ShowSummary();
                BundleNow("practice run finished");
                return;
            }

            // Phase A is complete and its data is written before anything asks the
            // participant to evaluate a room. That ordering is the whole reason the
            // review block does not contaminate the affect ratings.
            if (!DoesPhaseB)
            {
                Debug.Log("StudyBootstrap: Phase A only, session complete.");
                if (questionnaires != null) questionnaires.ShowSummary();
                if (board != null)
                    board.Show("That is everything.\n\nPlease take the headset off.");
                BundleNow("phase A finished");
                return;
            }

            Debug.Log("StudyBootstrap: main session finished, starting the review block.");
            oversightReview.BeginBlock();
        }

        void OnBlockFinished()
        {
            // The VR part is over. The after-forms are opened from the panel once the
            // headset is off -- NASA-TLX asks about the review block, so it wants to be
            // soon, but it does not want to be answered through a headset.
            if (questionnaires != null) questionnaires.ShowSummary();
            if (board != null)
                board.Show("That is everything.\n\nPlease take the headset off.");
            BundleNow("rooms and review finished");
        }

        /// <summary>Write the combined CSV. Runs itself, so nobody has to remember to.</summary>
        void BundleNow(string why)
        {
            string path = SessionBundle.Write(participantId);
            if (path == null)
            {
                Debug.LogWarning("StudyBootstrap: " + why + " for " + participantId +
                                 ", but there was nothing to bundle.");
                return;
            }
            Debug.Log("StudyBootstrap: " + why + " for " + participantId +
                      ". Everything combined into:\n  " + path);
        }

        void OnDetectionAnswered(string value, float confidence)
        {
            if (oversightReview == null) return;
            oversightReview.pendingDetectionConfidence = confidence;
            oversightReview.CommitDetection(value == "yes" ? false : true);
        }

        void OnAttributionAnswered(string value, float confidence)
        {
            if (oversightReview == null) return;
            oversightReview.pendingAttributionConfidence = confidence;
            oversightReview.CommitAttribution(value);
        }

        void OnCorrectionAnswered(string value, float confidence)
        {
            if (oversightReview != null) oversightReview.CommitCorrection(value);
        }

        QuestionPanel ActivePanel()
        {
            if (detectionPanel != null && detectionPanel.IsAwaitingAnswer) return detectionPanel;
            if (attributionPanel != null && attributionPanel.IsAwaitingAnswer) return attributionPanel;
            if (correctionPanel != null && correctionPanel.IsAwaitingAnswer) return correctionPanel;
            return null;
        }

        void Update()
        {
            PollWithdrawal();

            Ray ray;

            var panel = ActivePanel();
            if (panel != null)
            {
                if (!TryBuildRay(out ray)) return;
                panel.Hover(ray);
                if (useLegacyInput && Pressed()) panel.TrySelect(ray);
                return;
            }

            if (grid == null || !grid.IsAwaitingResponse) return;
            if (!TryBuildRay(out ray)) return;

            grid.Hover(ray);
            if (useLegacyInput && Pressed()) Select();
        }

        void PollWithdrawal()
        {
            if (Withdrawn || withdrawKey == KeyCode.None) return;

            if (!Input.GetKey(withdrawKey))
            {
                withdrawHeldSince = -1f;
                return;
            }

            if (withdrawHeldSince < 0f) withdrawHeldSince = Time.unscaledTime;
            else if (Time.unscaledTime - withdrawHeldSince >= withdrawHoldSeconds)
                WithdrawParticipant();
        }

        /// <summary>Commit whatever the pointer is currently over. Call from XR input.</summary>
        public void Select()
        {
            if (grid == null || !grid.IsAwaitingResponse) return;

            Ray ray;
            if (!TryBuildRay(out ray)) return;

            AffectResponse response;
            if (grid.TrySelect(ray, out response))
            {
                Debug.Log("StudyBootstrap: response " + response);
            }
        }

        bool TryBuildRay(out Ray ray)
        {
            // The controller wins whenever a headset is tracking, checked per frame so a
            // controller that wakes mid-session simply starts working.
            if (xrRig != null && xrRig.HeadsetPresent && xrRig.pointer != null)
            {
                ray = new Ray(xrRig.pointer.position, xrRig.pointer.forward);
                return true;
            }

            if (pointerOrigin != null)
            {
                ray = new Ray(pointerOrigin.position, pointerOrigin.forward);
                return true;
            }

            var camera = fallbackCamera != null ? fallbackCamera : Camera.main;
            if (camera == null)
            {
                ray = default(Ray);
                return false;
            }

            ray = camera.ScreenPointToRay(Input.mousePosition);
            return true;
        }

        bool Pressed()
        {

            if (!string.IsNullOrEmpty(selectButton))
            {
                // Wrapped: an unmapped axis name throws rather than returning false, and
                // a study should not die mid-session because of an inspector typo.
                try { return Input.GetButtonDown(selectButton); }
                catch (System.ArgumentException)
                {
                    Debug.LogWarning("StudyBootstrap: no input button named '" +
                                     selectButton + "'; falling back to mouse.");
                    selectButton = "";
                }
            }
            if (xrRig != null && xrRig.HeadsetPresent && XRRig.TriggerPressed()) return true;

            return Input.GetMouseButtonDown(0);
        }
    }
}
